/* eslint-disable no-unused-vars, react-refresh/only-export-components */
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const languages = {
  en: {
    name: 'English',
    dir: 'ltr',
    translations: {
      welcome: 'Welcome to Passwala',
      tagline: 'Your Trusted Neighborhood Hub',
      near_shops: 'Near Shops',
      expert_services: 'Local Experts',
      community: 'Community',
      essentials: 'Daily Essentials',
      search_placeholder: 'Search for shops or services...',
      add_to_cart: 'Add to Cart',
      book_now: 'Book Now',
      checkout: 'Checkout',
      cart_empty: 'Your cart is empty',
      savings: 'You saved',
      vendor_mode: 'Switch to Vendor Mode',
      profile: 'Profile',
      logout: 'Sign Out',
      location: 'Current Location',
      change_location: 'Change Location',
      trust_badge: 'Trusted by {n} neighbors',
      new_order: 'New Order',
      total: 'Total',
      items: 'Items',
      ai_expert: 'Chat with AI Expert',
      
      // Profile Page Translations
      appearance: 'Appearance',
      dark_mode: 'Dark Mode',
      switch_theme: 'Switch theme style',
      account_activity: 'Account & Activity',
      order_history: 'Order History',
      view_past_bookings: 'View your past bookings',
      passwala_wallet: 'Passwala Wallet',
      manage_credits: 'Manage your credits',
      delivery_address: 'Delivery Address',
      manage_locations: 'Manage your locations',
      data_safety_deletion: 'Data Safety & Deletion',
      manage_data_rights: 'Manage your data rights',
      privacy_security: 'Privacy & Security',
      manage_security: 'Manage your security',
      help_support: 'Help & Support',
      support_24_7: '24/7 support available',
      settings: 'Settings',
      app_preferences: 'App preferences',
      logout_session: 'Logout of your session',
      delete_account_permanently: 'Delete Account Permanently',
      
      // Hub Translations
      verified_pros: 'Verified local pros',
      best_stores: 'Best neighborhood stores',
      city_rides: 'City Rides',
      city_rides_sub: 'Ahmedabad transit',
      event_tickets: 'Event Tickets',
      event_tickets_sub: 'Ahmedabad events',
      join_floor_chat: 'JOIN FLOOR CHAT',
      book_pro: 'BOOK PRO',
      book_now_caps: 'BOOK NOW',
      book_ticket: 'Book Ticket',
      
      // Near Shops / Experts Translations
      search_shops_items: 'Search shops, items...',
      search_experts_services: 'Search experts, services...',
      all: 'All',
      general_store: 'General Store',
      grocery: 'Grocery',
      vegetables: 'Vegetables',
      dairy: 'Dairy',
      bakery: 'Bakery',
      plumbing: 'Plumbing',
      electrical: 'Electrical',
      ac_service: 'AC Service',
      cleaning: 'Cleaning',
      carpentry: 'Carpentry',
      ac_appliance: 'AC & Appliance',
      painting: 'Painting',
      grocery_essentials: 'Grocery & Essentials',
      fruits_vegetables: 'Fruits & Vegetables',
      dairy_bread_eggs: 'Dairy, Bread & Eggs',
      beverages_munchies: 'Beverages & Munchies',
      personal_care_hygiene: 'Personal Care & Hygiene',
      household_pet_care: 'Household & Pet Care',
      plumbing_services: 'Plumbing Services',
      electrical_services: 'Electrical Services',
      home_cleaning_deep_clean: 'Home Cleaning & Deep Clean',
      ac_appliance_repair: 'AC & Appliance Repair',
      pest_control_services: 'Pest Control Services',
      home_painting_decor: 'Home Painting & Decor',
      describe_issue: 'Describe issue (e.g. leaking tap, AC service)...',
      inspection_fee: 'Inspection Fee',
      km_away: '{dist} km away',
      you_are_here: 'You are here',
      view_services: 'View Services',
      view_catalog: 'View Catalog',
      book_expert: 'Book Expert',
      pickup_location: 'PICKUP LOCATION',
      dropoff_location: 'DROP-OFF LOCATION',
      search_pickup_placeholder: 'Search pickup location or tap map...',
      search_dropoff_placeholder: 'Search drop-off location or tap map...',
      popular_areas: 'Popular Areas in Ahmedabad',
      search_available_rides: 'Search Available Rides',
      confirm_ride: 'Confirm Ride',
      route_details: 'Route Details',
      available_vehicle: 'Available Vehicle',
      luggage_options: 'Luggage / Package Weight (Optional)',
      luggage_weight: 'Luggage weight: {w} kg',
      gst_tax: 'GST (5%)',
      total_fare: 'Total Fare',
      book_ticket_btn: 'Book Ticket',
      back_to_search: 'Back to Search',
      distance_unknown: 'Distance Unknown',
      km_from_you: '{dist} km from you',
      no_shops_found: 'No matching shops found',
      no_shops_found_sub: 'Try searching for a different category or store name in your area.',
      service_portfolio: 'Service Portfolio',
      digital_catalog: 'Digital Catalog',
      available_services: 'Available Services',
      available_products: 'Available Products',
      out_of_stock: 'Out of Stock',
      no_services_available: 'No services available right now.',
      no_products_available: 'No products available right now.',
      wallet_balance_title: 'AVAILABLE BALANCE',
      add_money: 'Add Money',
      send_money: 'Send Money',
      rewards: 'Rewards',
      recent_transactions: 'RECENT TRANSACTIONS',
      see_all: 'SEE ALL',
      rbi_sandbox_title: 'Passwala Wallet Beta (RBI Sandbox)',
      rbi_sandbox_desc: 'Peer wallet balances and transaction features are currently running in mock/demo mode undergoing sandbox regulatory audits.',
      bank_grade_encryption: 'Bank-Grade Encryption',
      bank_grade_encryption_sub: 'Your transactions are 100% secure with Passwala Trust Shield.',
      top_questions: 'TOP QUESTIONS',
      still_need_help: 'STILL NEED HELP?',
      whatsapp_support: 'WhatsApp Support',
      whatsapp_support_sub: 'Instant reply within 5 mins',
      email_support: 'Email Support',
      email_support_sub: 'We reply within 24 hours',
      call_support: 'Call Support',
      call_support_sub: 'Mon – Sat, 10 AM – 7 PM',
      app_version: 'App Version 2.0.4 Premium',
      account_security: 'Account Security',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      security_fully_secured: 'Your account is fully secured.',
      security_medium_tip: 'Turn on App Lock to reach high security level.',
      security_low_tip: 'Turn on 2FA and App Lock to secure your account.',
      security_controls: 'SECURITY CONTROLS',
      two_factor: 'Two-Factor Authentication',
      two_factor_sub: 'Enable 2FA for account safety',
      app_lock: 'App Lock',
      app_lock_sub: 'Secure app with biometric lock',
      privacy_policy_title: 'Privacy Policy',
      privacy_policy_sub: 'Read our data usage policy',
      data_management: 'Data Management',
      data_management_sub: 'Export or manage your data',
      encryption_note: 'Your connection to Passwala is encrypted with 256-bit SSL technology. No one, not even Passwala, can see your real-time private location except for verified orders.',
      rate_order: 'Rate Your Order',
      order_no: 'Order',
      rate_order_cta: 'Rate Order',
      rated_badge: 'Rated',
      write_review: 'Write your review...',
      submit_rating: 'Submit',
      order_history_title: 'Order History',
      community_feed: 'Community Feed',
      gathering_updates: 'Gathering neighborhood updates...',
      whats_on_mind: "What's on your mind?",
      post: 'Post',
      paste_image_url: 'Paste image URL here...',
      no_updates_yet: 'No real updates yet. Be the first!',
      verified: 'VERIFIED',
      second_btn: 'Second',
      feed: 'Feed',
      groups: 'Groups',
      safety: 'Safety',
      for_sale: 'For Sale',
      join: 'Join',
      digital_ticket: 'Digital Ticket',
      no_ticket_found: 'No Ticket Found',
      no_ticket_found_sub: "It looks like you haven't booked a city ride yet. Book one now and track it here!",
      book_city_ride: 'Book a City Ride',
      finding_driver: 'Finding a Driver...',
      ride_confirmed: 'Ride Confirmed',
      driver_arrived: 'Driver Arrived',
      ride_in_progress: 'Ride in Progress',
      ride_completed: 'Ride Completed',
      ride_cancelled: 'Ride Cancelled',
      finding_driver_sub: 'Please wait while we assign a rider to your booking',
      show_qr_to_driver: 'Show this QR code to the driver',
      driver_arrived_sub: 'Your driver has arrived at the pickup location',
      way_to_destination: 'You are on your way to the destination',
      thanks_riding: 'Thank you for riding with Passwala!',
      booking_cancelled_sub: 'This booking has been cancelled',
      time_to_destination: 'Time to Destination',
      driver_arrival_time: 'Driver Arrival Time',
      estimated_dropoff: 'Estimated Drop-off',
      ticket_id: 'Ticket ID',
      seats_booked: 'Seats Booked',
      luggage_weight_label: 'Luggage Weight',
      cancel_ride: 'Cancel Ride',
      back: 'Back',
      active_orders_label: 'ACTIVE ORDERS',
      syncing_cloud: 'Syncing neighborhood cloud...',
      ordered: 'Ordered',
      shipped: 'Shipped',
      delivery: 'Delivery',
      expert_on_way: 'Expert on the way',
      live_tracking_active: 'Live Tracking Active',
      preparing_kit: 'Preparing Kit...',
      preparing_order: 'Preparing Order...',
      waiting_expert: 'Waiting for Expert...',
      waiting_rider: 'Waiting for Rider...',
      waiting_confirmation: 'Waiting for confirmation...',
      confirming_order: 'Confirming order...',
      arrived_excl: 'Arrived!',
      arriving_in: 'Arriving in {time}',
      waiting_confirm_sub: 'Waiting for service provider to confirm booking...',
      confirming_order_sub: 'Confirming order with nearby riders...',
      booking_confirmed_sub: 'Booking Confirmed, preparing service kit',
      rider_assigned_sub: 'Rider Assigned, heading to the store',
      expert_preparing_sub: 'Expert is preparing for service visit',
      rider_picking_sub: 'Rider is at the store picking up',
      expert_on_way_sub: 'Expert is on the way to you',
      rider_on_way_sub: 'Rider is on the way to you',
      cancel: 'Cancel',
      details: 'Details',
      verified_partner: 'Verified Partner',
      verified_expert: 'Verified Expert',
      verified_agent: 'Verified Agent',
      active_orders: 'ACTIVE ORDERS',
      more: 'more',
      delivery_location: 'Delivery Location',
      service_location: 'Service Location',
      partner: 'Partner',
      service_expert: 'Service Expert',
      booked: 'Booked',
      en_route: 'En Route',
      service: 'Service',
      service_completed: 'Service Completed',
      delivered: 'Delivered',
      no_active_orders: 'No Active Orders',
      no_active_orders_sub: "You don't have any ongoing deliveries at the moment.",
      active_ride_bookings: 'Active Ride Bookings',
      confirmed: 'CONFIRMED',
      seats: 'seats',
      driver_live: 'Driver Live',
      awaiting_driver: 'Awaiting driver',
      driver_en_route: 'Driver En Route',
      preparing_ride: 'Preparing Ride',
      ride_confirmed_board: 'Ride Confirmed — Board at pickup point',
      show_qr_code_driver: 'Show QR code to driver. Seat(s) reserved.',
      view_ticket: 'View Ticket',
      my_event_tickets: 'My Event Tickets',
      previous_orders: 'Previous Orders',
      rate: 'Rate',
      rated: 'Rated',
      fulfilled: 'Fulfilled',
      cancelled: 'Cancelled',
      no_history_available: 'No history available yet.',
      cancel_order_confirm_title: 'Cancel Order?',
      cancel_order_confirm_desc: 'Are you sure you want to cancel this order? This action cannot be undone.',
      no_keep_it: 'No, Keep It',
      yes_cancel: 'Yes, Cancel',
      order_details: 'Order Details',
      invoice: 'Invoice',
      service_address: 'Service Address',
      items_summary: 'Items Summary',
      details_not_available: 'Details not available',
      total_refunded_paytm: 'Total Refunded (Paytm)',
      total_paid: 'Total Paid',
      payment_info: 'Payment Info',
      refunded_to_paytm: 'Refunded to Paytm',
      paid_online: 'Paid Online',
      transaction_id: 'Transaction ID',
      refunded: 'REFUNDED',
      success: 'SUCCESS',
      rate_your_experience: 'Rate Your Experience',
      your_rating: 'Your Rating',
      already_rated_msg: 'You have already submitted feedback for this order. Thank you!',
      help_improve_service: 'Help us improve our service',
      rate_now: 'Rate Now',
      rate_order_title: 'Rate Order',
      tell_us_more: 'Tell us more (optional)...',
      select_rating_above: 'Select a rating above',
      submitting: 'Submitting...',
      submit_rating_btn: 'Submit Rating',
      feedback_goes_to_store: 'Your feedback goes directly to the store',
      coming_soon: 'Coming Soon',
      rating_1: 'Terrible 😞',
      rating_2: 'Not Good 😕',
      rating_3: 'Okay 🙂',
      rating_4: 'Very Good 😊',
      rating_5: 'Excellent! 🤩',
      events_near_you: 'Events Near You',
      upcoming: 'Upcoming',
      past: 'Past',
      search_events_placeholder: 'Search events, concerts, workshops...',
      all_show_types: 'All Show Types',
      single_show: 'Single Show',
      multiple_shows: 'Multiple Shows',
      tour_festival: 'Tour / Festival',
      events_found: 'events found',
      event_found: 'event found',
      loading_events: 'Loading events...',
      no_events_found: 'No {filter} events found',
      show_all_events: 'Show all events',
      sold_out: 'SOLD OUT',
      onwards: 'onwards',
      only_n_left: 'Only {n} left!',
      n_available: '{n} available',
      prev: 'Prev',
      next: 'Next',
      cat_all: 'All',
      cat_music_concerts: 'Music & Concerts',
      cat_comedy_theatre: 'Comedy & Theatre',
      cat_workshops_classes: 'Workshops & Classes',
      cat_parties_nightlife: 'Parties & Nightlife',
      cat_festivals_fairs: 'Festivals & Fairs',
      cat_sports_fitness: 'Sports & Fitness',
      cat_corporate_business: 'Corporate & Business'
    }
  },
  hi: {
    name: 'हिंदी',
    dir: 'ltr',
    translations: {
      welcome: 'पासवाला में आपका स्वागत है',
      tagline: 'आपका भरोसेमंद पड़ोसी केंद्र',
      near_shops: 'पास की दुकानें',
      expert_services: 'स्थानीय विशेषज्ञ',
      community: 'समुदाय',
      essentials: 'दैनिक आवश्यकताएं',
      search_placeholder: 'दुकानें या सेवाएँ खोजें...',
      add_to_cart: 'कार्ट में जोड़ें',
      book_now: 'अभी बुक करें',
      checkout: 'चेकआउट',
      cart_empty: 'आपकी कार्ट खाली है',
      savings: 'आपने बचाए',
      vendor_mode: 'विक्रेता मोड पर स्विच करें',
      profile: 'प्रोफ़ाइल',
      logout: 'साइन आउट',
      location: 'वर्तमान स्थान',
      change_location: 'स्थान बदलें',
      trust_badge: '{n} पड़ोसियों का भरोसा',
      new_order: 'नया ऑर्डर',
      total: 'कुल',
      items: 'वस्तुएं',
      ai_expert: 'एआई विशेषज्ञ से चैट करें',
      
      // Profile Page Translations
      appearance: 'दिखावट',
      dark_mode: 'डार्क मोड',
      switch_theme: 'थीम शैली बदलें',
      account_activity: 'खाता और गतिविधि',
      order_history: 'ऑर्डर इतिहास',
      view_past_bookings: 'अपनी पुरानी बुकिंग देखें',
      passwala_wallet: 'पासवाला वॉलेट',
      manage_credits: 'अपने क्रेडिट प्रबंधित करें',
      delivery_address: 'डिलिवरी का पता',
      manage_locations: 'अपने स्थान प्रबंधित करें',
      data_safety_deletion: 'डेटा सुरक्षा और हटाना',
      manage_data_rights: 'अपने डेटा अधिकारों को प्रबंधित करें',
      privacy_security: 'गोपनीयता और सुरक्षा',
      manage_security: 'अपनी सुरक्षा प्रबंधित करें',
      help_support: 'सहायता और समर्थन',
      support_24_7: '24/7 सहायता उपलब्ध',
      settings: 'सेटिंग्स',
      app_preferences: 'ऐप प्राथमिकताएं',
      logout_session: 'अपने सत्र से लॉगआउट करें',
      delete_account_permanently: 'स्थायी रूप से खाता हटाएं',
      
      // Hub Translations
      verified_pros: 'सत्यापित स्थानीय पेशेवर',
      best_stores: 'सर्वश्रेष्ठ स्थानीय दुकानें',
      city_rides: 'शहर की सवारी',
      city_rides_sub: 'अहमदाबाद परिवहन',
      event_tickets: 'इवेंट टिकट',
      event_tickets_sub: 'अहमदाबाद के कार्यक्रम',
      join_floor_chat: 'चैट में शामिल हों',
      book_pro: 'प्रो बुक करें',
      book_now_caps: 'अभी बुक करें',
      book_ticket: 'टिकट बुक करें',
      
      // Near Shops / Experts Translations
      search_shops_items: 'दुकानें, सामान खोजें...',
      search_experts_services: 'विशेषज्ञ, सेवाएँ खोजें...',
      all: 'सभी',
      general_store: 'जनरल स्टोर',
      grocery: 'किराना',
      vegetables: 'सब्जियां',
      dairy: 'डेयरी',
      bakery: 'बेकरी',
      plumbing: 'प्लंबिंग',
      electrical: 'इलेक्ट्रिकल',
      ac_service: 'एसी सर्विस',
      cleaning: 'सफाई',
      carpentry: 'बढ़ईगीरी',
      ac_appliance: 'एसी और उपकरण',
      painting: 'पेंटिंग',
      grocery_essentials: 'किराना और आवश्यक वस्तुएं',
      fruits_vegetables: 'फल और सब्जियां',
      dairy_bread_eggs: 'डेयरी, ब्रेड और अंडे',
      beverages_munchies: 'पेय और नाश्ता',
      personal_care_hygiene: 'व्यक्तिगत देखभाल और स्वच्छता',
      household_pet_care: 'घरेलू और पालतू जानवरों की देखभाल',
      plumbing_services: 'प्लंबिंग सेवाएं',
      electrical_services: 'इलेक्ट्रिकल सेवाएं',
      home_cleaning_deep_clean: 'घर की सफाई और डीप क्लीन',
      ac_appliance_repair: 'एसी और उपकरण मरम्मत',
      pest_control_services: 'कीट नियंत्रण सेवाएं',
      home_painting_decor: 'घर की पेंटिंग और सजावट',
      describe_issue: 'समस्या का वर्णन करें (जैसे कि नल टपकना, एसी सेवा)...',
      inspection_fee: 'निरीक्षण शुल्क',
      km_away: '{dist} किमी दूर',
      you_are_here: 'आप यहाँ हैं',
      view_services: 'सेवाएँ देखें',
      view_catalog: 'कैटलॉग देखें',
      book_expert: 'विशेषज्ञ बुक करें',
      pickup_location: 'पिकअप स्थान',
      dropoff_location: 'ड्रॉप-ऑफ स्थान',
      search_pickup_placeholder: 'पिकअप स्थान खोजें या मानचित्र पर टैप करें...',
      search_dropoff_placeholder: 'ड्रॉप-ऑफ स्थान खोजें या मानचित्र पर टैप करें...',
      popular_areas: 'अहमदाबाद में लोकप्रिय क्षेत्र',
      search_available_rides: 'उपलब्ध सवारियां खोजें',
      confirm_ride: 'सवारी की पुष्टि करें',
      route_details: 'मार्ग विवरण',
      available_vehicle: 'उपलब्ध वाहन',
      luggage_options: 'सामान / पैकेज का वजन (वैकल्पिक)',
      luggage_weight: 'सामान का वजन: {w} किग्रा',
      gst_tax: 'जीएसटी (5%)',
      total_fare: 'कुल किराया',
      book_ticket_btn: 'टिकट बुक करें',
      back_to_search: 'खोज पर वापस जाएं',
      distance_unknown: 'दूरी अज्ञात',
      km_from_you: 'आपसे {dist} किमी',
      no_shops_found: 'कोई मेल खाती दुकानें नहीं मिलीं',
      no_shops_found_sub: 'अपने क्षेत्र में एक अलग श्रेणी या स्टोर नाम खोजने का प्रयास करें।',
      service_portfolio: 'सेवा पोर्टफोलियो',
      digital_catalog: 'डिजिटल कैटलॉग',
      available_services: 'उपलब्ध सेवाएं',
      available_products: 'उपलब्ध उत्पाद',
      out_of_stock: 'आउट ऑफ स्टॉक',
      no_services_available: 'अभी कोई सेवाएं उपलब्ध नहीं हैं।',
      no_products_available: 'अभी कोई उत्पाद उपलब्ध नहीं हैं।',
      wallet_balance_title: 'उपलब्ध शेष राशि',
      add_money: 'पैसे जोड़ें',
      send_money: 'पैसे भेजें',
      rewards: 'पुरस्कार',
      recent_transactions: 'हाल ही के लेन-देन',
      see_all: 'सभी देखें',
      rbi_sandbox_title: 'पासवाला वॉलेट बीटा (RBI सैंडबॉक्स)',
      rbi_sandbox_desc: 'सहकर्मी वॉलेट बैलेंस और लेन-देन सुविधाएँ वर्तमान में मॉक/डेमो मोड में चल रही हैं और सैंडबॉक्स नियामक ऑडिट के अधीन हैं।',
      bank_grade_encryption: 'बैंक-ग्रेड एन्क्रिप्शन',
      bank_grade_encryption_sub: 'पासवाला ट्रस्ट शील्ड के साथ आपके लेनदेन 100% सुरक्षित हैं।',
      top_questions: 'शीर्ष प्रश्न',
      still_need_help: 'अभी भी सहायता चाहिए?',
      whatsapp_support: 'व्हाट्सएप सहायता',
      whatsapp_support_sub: '5 मिनट के भीतर त्वरित उत्तर',
      email_support: 'ईमेल सहायता',
      email_support_sub: 'हम 24 घंटे के भीतर उत्तर देते हैं',
      call_support: 'कॉल सहायता',
      call_support_sub: 'सोम – शनि, सुबह 10 – शाम 7 बजे',
      app_version: 'ऐप संस्करण 2.0.4 प्रीमियम',
      account_security: 'खाता सुरक्षा',
      high: 'उच्च',
      medium: 'मध्यम',
      low: 'कम',
      security_fully_secured: 'आपका खाता पूरी तरह से सुरक्षित है।',
      security_medium_tip: 'उच्च सुरक्षा स्तर तक पहुँचने के लिए ऐप लॉक चालू करें।',
      security_low_tip: 'अपने खाते को सुरक्षित करने के लिए 2FA और ऐप लॉक चालू करें।',
      security_controls: 'सुरक्षा नियंत्रण',
      two_factor: 'दो-कारक प्रमाणीकरण',
      two_factor_sub: 'खाता सुरक्षा के लिए 2FA सक्षम करें',
      app_lock: 'ऐप लॉक',
      app_lock_sub: 'बायोमेट्रिक लॉक से ऐप सुरक्षित करें',
      privacy_policy_title: 'गोपनीयता नीति',
      privacy_policy_sub: 'हमारी डेटा उपयोग नीति पढ़ें',
      data_management: 'डेटा प्रबंधन',
      data_management_sub: 'अपने डेटा को प्रबंधित या निर्यात करें',
      encryption_note: 'पासवाला से आपका कनेक्शन 256-बिट SSL तकनीक से एन्क्रिप्टेड है। सत्यापित ऑर्डर को छोड़कर कोई भी, पासवाला भी, आपका रीयल-टाइम निजी स्थान नहीं देख सकता है।',
      rate_order: 'अपने ऑर्डर को रेट करें',
      order_no: 'ऑर्डर',
      rate_order_cta: 'ऑर्डर रेट करें',
      rated_badge: 'रेटेड',
      write_review: 'समीक्षा लिखें...',
      submit_rating: 'जमा करें',
      order_history_title: 'ऑर्डर इतिहास',
      community_feed: 'सामुदायिक फ़ीड',
      gathering_updates: 'पड़ोस के अपडेट एकत्र किए जा रहे हैं...',
      whats_on_mind: 'आपके मन में क्या है?',
      post: 'पोस्ट',
      paste_image_url: 'यहाँ छवि URL पेस्ट करें...',
      no_updates_yet: 'अभी तक कोई वास्तविक अपडेट नहीं है। पहले बनें!',
      verified: 'सत्यापित',
      second_btn: 'सहमति',
      feed: 'फ़ीड',
      groups: 'समूह',
      safety: 'सुरक्षा',
      for_sale: 'बिक्री के लिए',
      join: 'शामिल हों',
      digital_ticket: 'डिजिटल टिकट',
      no_ticket_found: 'कोई टिकट नहीं मिला',
      no_ticket_found_sub: 'ऐसा लगता है कि आपने अभी तक शहर की सवारी बुक नहीं की है। अभी एक बुक करें और इसे यहाँ ट्रैक करें!',
      book_city_ride: 'शहर की सवारी बुक करें',
      finding_driver: 'ड्राइवर की तलाश की जा रही है...',
      ride_confirmed: 'सवारी की पुष्टि हो गई',
      driver_arrived: 'ड्राइवर पहुँच गया',
      ride_in_progress: 'सवारी प्रगति पर है',
      ride_completed: 'सवारी पूरी हो गई',
      ride_cancelled: 'सवारी रद्द कर दी गई',
      finding_driver_sub: 'कृपया प्रतीक्षा करें जब तक हम आपकी बुकिंग के लिए एक राइडर असाइन करते हैं',
      show_qr_to_driver: 'ड्राइवर को यह क्यूआर कोड दिखाएं',
      driver_arrived_sub: 'आपका ड्राइवर पिकअप स्थान पर पहुँच गया है',
      way_to_destination: 'आप गंतव्य के रास्ते पर हैं',
      thanks_riding: 'पासवाला के साथ सवारी करने के लिए धन्यवाद!',
      booking_cancelled_sub: 'यह बुकिंग रद्द कर दी गई है',
      time_to_destination: 'गंतव्य का समय',
      driver_arrival_time: 'ड्राइवर के आगमन का समय',
      estimated_dropoff: 'अनुमानित ड्रॉप-ऑफ',
      ticket_id: 'टिकट आईडी',
      seats_booked: 'बुक की गई सीटें',
      luggage_weight_label: 'सामान का वजन',
      cancel_ride: 'सवारी रद्द करें',
      back: 'पीछे',
      active_orders_label: 'सक्रिय ऑर्डर',
      syncing_cloud: 'पड़ोस क्लाउड को सिंक किया जा रहा है...',
      ordered: 'ऑर्डर किया गया',
      shipped: 'भेज दिया गया',
      delivery: 'डिलिवरी',
      expert_on_way: 'विशेषज्ञ रास्ते पर है',
      live_tracking_active: 'लाइव ट्रैकिंग सक्रिय',
      preparing_kit: 'किट तैयार की जा रही है...',
      preparing_order: 'ऑर्डर तैयार किया जा रहा है...',
      waiting_expert: 'विशेषज्ञ का इंतजार...',
      waiting_rider: 'राइडर का इंतजार...',
      waiting_confirmation: 'पुष्टि का इंतजार...',
      confirming_order: 'ऑर्डर की पुष्टि की जा रही है...',
      arrived_excl: 'पहुँच गए!',
      arriving_in: '{time} में आगमन',
      waiting_confirm_sub: 'बुकिंग की पुष्टि करने के लिए सेवा प्रदाता की प्रतीक्षा की जा रही है...',
      confirming_order_sub: 'आस-पास के राइडर्स के साथ ऑर्डर की पुष्टि की जा रही है...',
      booking_confirmed_sub: 'बुकिंग की पुष्टि हो गई, सेवा किट तैयार की जा रही है',
      rider_assigned_sub: 'राइडर असाइन किया गया, दुकान की ओर जा रहा है',
      expert_preparing_sub: 'विशेषज्ञ सेवा यात्रा की तैयारी कर रहा है',
      rider_picking_sub: 'राइडर दुकान पर सामान उठा रहा है',
      expert_on_way_sub: 'विशेषज्ञ आपके पास आ रहा है',
      rider_on_way_sub: 'राइडर आपके पास आ रहा है',
      cancel: 'रद्द करें',
      details: 'विवरण',
      verified_partner: 'सत्यापित भागीदार',
      verified_expert: 'सत्यापित विशेषज्ञ',
      verified_agent: 'सत्यापित एजेंट',
      active_orders: 'सक्रिय ऑर्डर',
      more: 'और',
      delivery_location: 'डिलिवरी स्थान',
      service_location: 'सेवा स्थान',
      partner: 'भागीदार',
      service_expert: 'सेवा विशेषज्ञ',
      booked: 'बुक किया गया',
      en_route: 'रास्ते में',
      service: 'सेवा',
      service_completed: 'सेवा पूरी हुई',
      delivered: 'डिलिवर किया गया',
      no_active_orders: 'कोई सक्रिय ऑर्डर नहीं',
      no_active_orders_sub: "आपके पास इस समय कोई सक्रिय डिलीवरी नहीं है।",
      active_ride_bookings: 'सक्रिय सवारी बुकिंग',
      confirmed: 'पुष्टि की गई',
      seats: 'सीटें',
      driver_live: 'ड्राइवर लाइव',
      awaiting_driver: 'ड्राइवर की प्रतीक्षा',
      driver_en_route: 'ड्राइवर रास्ते में है',
      preparing_ride: 'सवारी तैयार की जा रही है',
      ride_confirmed_board: 'सवारी की पुष्टि — पिकअप बिंदु पर सवार हों',
      show_qr_code_driver: 'ड्राइवर को क्यूआर कोड दिखाएं। सीट आरक्षित।',
      view_ticket: 'टिकट देखें',
      my_event_tickets: 'मेरे इवेंट टिकट',
      previous_orders: 'पिछले ऑर्डर',
      rate: 'रेट करें',
      rated: 'रेटेड',
      fulfilled: 'पूरा हुआ',
      cancelled: 'रद्द किया गया',
      no_history_available: 'अभी तक कोई इतिहास उपलब्ध नहीं है।',
      cancel_order_confirm_title: 'ऑर्डर रद्द करें?',
      cancel_order_confirm_desc: 'क्या आप वाकई इस ऑर्डर को रद्द करना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
      no_keep_it: 'नहीं, रहने दें',
      yes_cancel: 'हां, रद्द करें',
      order_details: 'ऑर्डर का विवरण',
      invoice: 'इनवॉइस',
      service_address: 'सेवा का पता',
      items_summary: 'सामान का सारांश',
      details_not_available: 'विवरण उपलब्ध नहीं है',
      total_refunded_paytm: 'कुल धनवापसी (Paytm)',
      total_paid: 'कुल भुगतान',
      payment_info: 'भुगतान की जानकारी',
      refunded_to_paytm: 'Paytm में वापस किया गया',
      paid_online: 'ऑनलाइन भुगतान',
      transaction_id: 'लेन-देन आईडी',
      refunded: 'वापस किया गया',
      success: 'सफल',
      rate_your_experience: 'अपने अनुभव को रेट करें',
      your_rating: 'आपकी रेटिंग',
      already_rated_msg: 'आप पहले ही इस ऑर्डर के लिए फीडबैक सबमिट कर चुके हैं। धन्यवाद!',
      help_improve_service: 'हमारी सेवा को बेहतर बनाने में मदद करें',
      rate_now: 'अभी रेट करें',
      rate_order_title: 'ऑर्डर को रेट करें',
      tell_us_more: 'हमें और बताएं (वैकल्पिक)...',
      select_rating_above: 'ऊपर एक रेटिंग चुनें',
      submitting: 'सबमिट किया जा रहा है...',
      submit_rating_btn: 'रेटिंग सबमिट करें',
      feedback_goes_to_store: 'आपका फीडबैक सीधे स्टोर पर जाता है',
      coming_soon: 'जल्द आ रहा है',
      rating_1: 'बहुत खराब 😞',
      rating_2: 'अच्छा नहीं 😕',
      rating_3: 'ठीक है 🙂',
      rating_4: 'बहुत अच्छा 😊',
      rating_5: 'उत्कृष्ट! 🤩',
      events_near_you: 'आपके पास के कार्यक्रम',
      upcoming: 'आगामी',
      past: 'पुराने',
      search_events_placeholder: 'इवेंट, संगीत कार्यक्रम, कार्यशालाएं खोजें...',
      all_show_types: 'सभी शो प्रकार',
      single_show: 'एकल शो',
      multiple_shows: 'एकाधिक शो',
      tour_festival: 'टूर / महोत्सव',
      events_found: 'इवेंट मिले',
      event_found: 'इवेंट मिला',
      loading_events: 'इवेंट लोड किए जा रहे हैं...',
      no_events_found: 'कोई {filter} इवेंट नहीं मिला',
      show_all_events: 'सभी इवेंट दिखाएं',
      sold_out: 'बिक चुके हैं',
      onwards: 'से शुरू',
      only_n_left: 'केवल {n} बचे हैं!',
      n_available: '{n} उपलब्ध',
      prev: 'पिछला',
      next: 'अगला',
      cat_all: 'सभी',
      cat_music_concerts: 'संगीत और कार्यक्रम',
      cat_comedy_theatre: 'कॉमेडी और थिएटर',
      cat_workshops_classes: 'कार्यशालाएं और कक्षाएं',
      cat_parties_nightlife: 'पार्टी और नाइटलाइफ़',
      cat_festivals_fairs: 'महोत्सव और मेले',
      cat_sports_fitness: 'खेल और फिटनेस',
      cat_corporate_business: 'कॉर्पोरेट और व्यवसाय'
    }
  },
  gu: {
    name: 'ગુજરાતી',
    dir: 'ltr',
    translations: {
      welcome: 'પાસવાલામાં તમારું સ્વાગત છે',
      tagline: 'તમારા વિશ્વાસુ પડોશી હબ',
      near_shops: 'નજીકની દુકાનો',
      expert_services: 'સ્થાનિક નિષ્ણાતો',
      community: 'સમુદાય',
      essentials: 'દૈનિક જરૂરિયાતો',
      search_placeholder: 'દુકાનો કે સેવાઓ શોધો...',
      add_to_cart: 'કાર્ટમાં ઉમેરો',
      book_now: 'અત્યારે બુક કરો',
      checkout: 'ચેકઆઉટ',
      cart_empty: 'તમારી કાર્ટ ખાલી છે',
      savings: 'તમે બચાવ્યા',
      vendor_mode: 'વેન્ડર મોડ પર સ્વિચ કરો',
      profile: 'પ્રોફાઇલ',
      logout: 'સાઇન આઉટ',
      location: 'વર્તમાન સ્થાન',
      change_location: 'સ્થાન બદલો',
      trust_badge: '{n} પડોશીઓ દ્વારા વિશ્વાસ',
      new_order: 'નવો ઓર્ડર',
      total: 'કુલ',
      items: 'વસ્તુઓ',
      ai_expert: 'AI નિષ્ણાત સાથે ચેટ કરો',
      
      // Profile Page Translations
      appearance: 'દેખાવ',
      dark_mode: 'ડાર્ક મોડ',
      switch_theme: 'થીમ શૈલી બદલો',
      account_activity: 'ખાતું અને પ્રવૃત્તિ',
      order_history: 'ઓર્ડર ઇતિહાસ',
      view_past_bookings: 'તમારી ભૂતકાળની બુકિંગ જુઓ',
      passwala_wallet: 'પાસવાલા વોલેટ',
      manage_credits: 'તમારા ક્રેડિટ મેનેજ કરો',
      delivery_address: 'ડિલિવરી સરનામું',
      manage_locations: 'તમારા સ્થાનો મેનેજ કરો',
      data_safety_deletion: 'ડેટા સુરક્ષા અને કાઢી નાખવું',
      manage_data_rights: 'તમારા ડેટા અધિકારો મેનેજ કરો',
      privacy_security: 'ગોપનીયતા અને સુરક્ષા',
      manage_security: 'તમારી સુરક્ષા મેનેજ કરો',
      help_support: 'મદદ અને સપોર્ટ',
      support_24_7: '24/7 સપોર્ટ ઉપલબ્ધ',
      settings: 'સેટિંગ્સ',
      app_preferences: 'એપ્લિકેશન પસંદગીઓ',
      logout_session: 'તમારા સત્રમાંથી લોગઆઉટ કરો',
      delete_account_permanently: 'કાયમ માટે ખાતું કાઢી નાખો',
      
      // Hub Translations
      verified_pros: 'પ્રમાણિત સ્થાનિક વ્યાવસાયિકો',
      best_stores: 'શ્રેષ્ઠ પડોશી દુકાનો',
      city_rides: 'શહેરની સવારી',
      city_rides_sub: 'અમદાવાદ ટ્રાન્ઝિટ',
      event_tickets: 'ઇવેન્ટ ટિકિટ',
      event_tickets_sub: 'અમદાવાદ કાર્યક્રમો',
      join_floor_chat: 'ચેટમાં જોડાઓ',
      book_pro: 'પ્રો બુક કરો',
      book_now_caps: 'અત્યારે બુક કરો',
      book_ticket: 'ટિકિટ બુક કરો',
      
      // Near Shops / Experts Translations
      search_shops_items: 'દુકાનો, વસ્તુઓ શોધો...',
      search_experts_services: 'નિષ્ણાતો, સેવાઓ શોધો...',
      all: 'બધા',
      general_store: 'જનરલ સ્ટોર',
      grocery: 'કરિયાણું',
      vegetables: 'શાકભાજી',
      dairy: 'ડેરી',
      bakery: 'બેકરી',
      plumbing: 'પ્લમ્બિંગ',
      electrical: 'ઇલેક્ટ્રિકલ',
      ac_service: 'એસી સર્વિસ',
      cleaning: 'સફાઈ',
      carpentry: 'સુથારી કામ',
      ac_appliance: 'એસી અને ઉપકરણો',
      painting: 'પેઇન્ટિંગ',
      grocery_essentials: 'કરિયાણું અને આવશ્યક ચીજો',
      fruits_vegetables: 'ફળો અને શાકભાજી',
      dairy_bread_eggs: 'ડેરી, બ્રેડ અને ઇંડા',
      beverages_munchies: 'પીણાં અને નાસ્તો',
      personal_care_hygiene: 'વ્યક્તિગત સંભાળ અને સ્વચ્છતા',
      household_pet_care: 'ઘરગથ્થુ અને પાલતુ પ્રાણીઓની સંભાળ',
      plumbing_services: 'પ્લમ્બિંગ સેવાઓ',
      electrical_services: 'ઇલેક્ટ્રિકલ સેવાઓ',
      home_cleaning_deep_clean: 'ઘરની સફાઈ અને ડીપ ક્લીન',
      ac_appliance_repair: 'એસી અને સાધનોનું સમારકામ',
      pest_control_services: 'જંતુ નિયંત્રણ સેવાઓ',
      home_painting_decor: 'ઘર પેઇન્ટિંગ અને ડેકોર',
      describe_issue: 'સમસ્યાનું વર્ણન કરો (જેમ કે નળ ટપકવો, એસી સેવા)...',
      inspection_fee: 'નિરીક્ષણ ફી',
      km_away: '{dist} કિમી દૂર',
      you_are_here: 'તમે અહીં છો',
      view_services: 'સેવાઓ જુઓ',
      view_catalog: 'કેટલોગ જુઓ',
      book_expert: 'નિષ્ણાત બુક કરો',
      pickup_location: 'પિકઅપ સ્થાન',
      dropoff_location: 'ડ્રોપ-ઓફ સ્થાન',
      search_pickup_placeholder: 'પિકઅપ સ્થાન શોધો અથવા નકશા પર ટેપ કરો...',
      search_dropoff_placeholder: 'ડ્રોપ-ઓફ સ્થાન શોધો અથવા નકશા પર ટેપ કરો...',
      popular_areas: 'અમદાવાદમાં લોકપ્રિય વિસ્તારો',
      search_available_rides: 'ઉપલબ્ધ સવારી શોધો',
      confirm_ride: 'સવારી કન્ફર્મ કરો',
      route_details: 'રૂટ વિગતો',
      available_vehicle: 'ઉપલબ્ધ વાહન',
      luggage_options: 'સામાન / પેકેજ વજન (વૈકલ્પિક)',
      luggage_weight: 'સામાનનું વજન: {w} કિગ્રા',
      gst_tax: 'GST (5%)',
      total_fare: 'કુલ ભાડું',
      book_ticket_btn: 'ટિકિટ બુક કરો',
      back_to_search: 'શોધ પર પાછા ફરો',
      distance_unknown: 'અજ્ઞાત અંતર',
      km_from_you: 'તમારાથી {dist} કિમી',
      no_shops_found: 'કોઈ મેળ ખાતી દુકાનો મળી નથી',
      no_shops_found_sub: 'તમારા વિસ્તારમાં એક અલગ કેટેગરી અથવા સ્ટોર નામ શોધવાનો પ્રયાસ કરો.',
      service_portfolio: 'સેવા પોર્ટફોલિયો',
      digital_catalog: 'ડિજિટલ કેટલોગ',
      available_services: 'ઉપલબ્ધ સેવાઓ',
      available_products: 'ઉપલબ્ધ પ્રોડક્ટ્સ',
      out_of_stock: 'આઉટ ઓફ સ્ટોક',
      no_services_available: 'હમણાં કોઈ સેવાઓ ઉપલબ્ધ નથી.',
      no_products_available: 'હમણાં કોઈ પ્રોડક્ટ્સ ઉપલબ્ધ નથી.',
      wallet_balance_title: 'પ્રાપ્ત બેલેન્સ',
      add_money: 'પૈસા ઉમેરો',
      send_money: 'પૈસા મોકલો',
      rewards: 'ઇનામો',
      recent_transactions: 'તાજેતરના વ્યવહારો',
      see_all: 'બધું જુઓ',
      rbi_sandbox_title: 'પાસવાલા વોલેટ બીટા (RBI સેન્ડબોક્સ)',
      rbi_sandbox_desc: 'પીઅર વૉલેટ બેલેન્સ અને ટ્રાન્ઝેક્શન સુવિધાઓ હાલમાં સેન્ડબોક્સ રેગ્યુલેટરી ઓડિટ હેઠળ મોક/ડેમો મોડમાં ચાલી રહી છે.',
      bank_grade_encryption: 'બેંક-ગ્રેડ એન્ક્રિપ્શન',
      bank_grade_encryption_sub: 'તમારા વ્યવહારો પાસવાલા ટ્રસ્ટ શીલ્ડ વડે 100% સુરક્ષિત છે.',
      top_questions: 'મુખ્ય પ્રશ્નો',
      still_need_help: 'હજી મદદની જરૂર છે?',
      whatsapp_support: 'WhatsApp સપોર્ટ',
      whatsapp_support_sub: '5 મિનિટમાં ત્વરિત જવાબ',
      email_support: 'ઇમેઇલ સપોર્ટ',
      email_support_sub: 'અમે 24 કલાકની અંદર જવાબ આપીએ છીએ',
      call_support: 'કૉલ સપોર્ટ',
      call_support_sub: 'સોમ – શનિ, સવારે 10 – સાંજે 7 વાગ્યે',
      app_version: 'એપ્લિકેશન વર્ઝન 2.0.4 પ્રીમિયમ',
      account_security: 'ખાતાની સુરક્ષા',
      high: 'ઉચ્ચ',
      medium: 'મધ્યમ',
      low: 'ઓછું',
      security_fully_secured: 'તમારું ખાતું સંપૂર્ણપણે સુરક્ષિત છે.',
      security_medium_tip: 'ઉચ્ચ સુરક્ષા સ્તરે પહોંચવા માટે એપ લોક ચાલુ કરો.',
      security_low_tip: 'તમારા ખાતાને સુરક્ષિત કરવા માટે 2FA અને એપ લોક ચાલુ કરો.',
      security_controls: 'સુરક્ષા નિયંત્રણો',
      two_factor: 'ટુ-ફેક્ટર ઓથેન્ટિકેશન',
      two_factor_sub: 'ખાતાની સુરક્ષા માટે 2FA સક્ષમ કરો',
      app_lock: 'એપ લોક',
      app_lock_sub: 'બાયોમેટ્રિક લોક વડે એપ સુરક્ષિત કરો',
      privacy_policy_title: 'ગોપનીયતા નીતિ',
      privacy_policy_sub: 'અમારી ડેટા વપરાશ નીતિ વાંચો',
      data_management: 'ડેટા મેનેજમેન્ટ',
      data_management_sub: 'તમારા ડેટાને નિકાસ અથવા મેનેજ કરો',
      encryption_note: 'પાસવાલા સાથેનું તમારું જોડાણ 256-બીટ SSL ટેકનોલોજીથી એન્ક્રિપ્ટેડ છે. વેરિફાઇડ ઓર્ડર સિવાય કોઈ પણ, પાસવાલા પણ, તમારું રીઅલ-ટાઇમ ખાનગી સ્થાન જોઈ શકશે નહીં.',
      rate_order: 'તમારા ઓર્ડરને રેટ કરો',
      order_no: 'ઓર્ડર',
      rate_order_cta: 'ઓર્ડર રેટ કરો',
      rated_badge: 'રેટેડ',
      write_review: 'તમારી સમીક્ષા લખો...',
      submit_rating: 'સબમિટ',
      order_history_title: 'ઓર્ડર ઇતિહાસ',
      community_feed: 'સમુદાય ફીડ',
      gathering_updates: 'પડોશના અપડેટ્સ એકત્રિત કરવામાં આવી રહ્યા છે...',
      whats_on_mind: 'તમારા મનમાં શું છે?',
      post: 'પોસ્ટ',
      paste_image_url: 'અહીં છબી URL પેસ્ટ કરો...',
      no_updates_yet: 'હજુ સુધી કોઈ અપડેટ નથી. પહેલા બનો!',
      verified: 'પ્રમાણિત',
      second_btn: 'સંમતિ',
      feed: 'ફીડ',
      groups: 'જૂથો',
      safety: 'સુરક્ષા',
      for_sale: 'વેચાણ માટે',
      join: 'જોડાઓ',
      digital_ticket: 'ડિજિટલ ટિકિટ',
      no_ticket_found: 'કોઈ ટિકિટ મળી નથી',
      no_ticket_found_sub: 'એવું લાગે છે કે તમે હજી સુધી શહેરની સવારી બુક કરાવી નથી. અત્યારે બુક કરો અને તેને અહીં ટ્રેક કરો!',
      book_city_ride: 'શહેરની સવારી બુક કરો',
      finding_driver: 'ડ્રાઇવર શોધાઈ રહ્યો છે...',
      ride_confirmed: 'સવારી કન્ફર્મ થઈ',
      driver_arrived: 'ડ્રાઇવર આવી ગયો',
      ride_in_progress: 'સવારી ચાલુ છે',
      ride_completed: 'સવારી પૂર્ણ થઈ',
      ride_cancelled: 'સવારી રદ થઈ',
      finding_driver_sub: 'કૃપા કરીને રાહ જુઓ જ્યાં સુધી અમે તમારા બુકિંગ માટે રાઇડર સોંપીએ',
      show_qr_to_driver: 'ડ્રાઇવરને આ ક્યૂઆર કોડ બતાવો',
      driver_arrived_sub: 'તમારો ડ્રાઇવર પીકઅપ લોકેશન પર પહોંચી ગયો છે',
      way_to_destination: 'તમે ગંતવ્ય તરફ જઈ રહ્યા છો',
      thanks_riding: 'પાસવાલા સાથે સવારી કરવા બદલ આભાર!',
      booking_cancelled_sub: 'આ બુકિંગ રદ કરવામાં આવ્યું છે',
      time_to_destination: 'ગંતવ્ય સુધીનો સમય',
      driver_arrival_time: 'ડ્રાઇવર આગમન સમય',
      estimated_dropoff: 'અંદાજિત ડ્રોપ-ઓફ',
      ticket_id: 'ટિકિટ આઈડી',
      seats_booked: 'બુક કરેલી બેઠકો',
      luggage_weight_label: 'સામાનનું વજન',
      cancel_ride: 'સવારી રદ કરો',
      back: 'પાછા',
      active_orders_label: 'સક્રિય ઓર્ડર',
      syncing_cloud: 'પડોશ ક્લાઉડ સમન્વયિત થઈ રહ્યું છે...',
      ordered: 'ઓર્ડર કરેલ',
      shipped: 'મોકલેલ',
      delivery: 'ડિલિવરી',
      expert_on_way: 'નિષ્ણાત રસ્તામાં છે',
      live_tracking_active: 'લાઇવ ટ્રેકિંગ સક્રિય',
      preparing_kit: 'કિટ તૈયાર થઈ રહી છે...',
      preparing_order: 'ઓર્ડર તૈયાર થઈ રહ્યો છે...',
      waiting_expert: 'નિષ્ણાતની રાહ જોઈ રહ્યા છીએ...',
      waiting_rider: 'રાઇડરની રાહ જોઈ રહ્યા છીએ...',
      waiting_confirmation: 'પુષ્ટિની રાહ જોઈ રહ્યા છીએ...',
      confirming_order: 'ઓર્ડરની પુષ્ટિ કરવામાં આવી રહી છે...',
      arrived_excl: 'આવી ગયા!',
      arriving_in: '{time} માં આગમન',
      waiting_confirm_sub: 'બુકિંગ કન્ફર્મ કરવા માટે સેવા પ્રદાતાની રાહ જોઈ રહ્યા છીએ...',
      confirming_order_sub: 'નજીકના રાઇડર્સ સાથે ઓર્ડર કન્ફર્મ કરવામાં આવી રહ્યો છે...',
      booking_confirmed_sub: 'બુકિંગ કન્ફર્મ થયું, સેવા કીટ તૈયાર કરવામાં આવી રહી છે',
      rider_assigned_sub: 'રાઇડર સોંપવામાં આવ્યો, સ્ટોર તરફ જઈ રહ્યો છે',
      expert_preparing_sub: 'નિષ્ણાત સેવા મુલાકાતની તૈયારી કરી રહ્યો છે',
      rider_picking_sub: 'રાઇડર સ્ટોર પરથી સામાન મેળવી રહ્યો છે',
      expert_on_way_sub: 'નિષ્ણાત તમારી તરફ આવી રહ્યો છે',
      rider_on_way_sub: 'રાઇડર તમારી તરફ આવી રહ્યો છે',
      cancel: 'રદ કરો',
      details: 'વિગતો',
      verified_partner: 'પ્રમાણિત ભાગીદાર',
      verified_expert: 'પ્રમાણિત નિષ્ણાત',
      verified_agent: 'પ્રમાણિત એજન્ટ',
      active_orders: 'સક્રિય ઓર્ડર',
      more: 'વધુ',
      delivery_location: 'ડિલિવરી સ્થાન',
      service_location: 'સેવા સ્થાન',
      partner: 'ભાગીદાર',
      service_expert: 'સેવા નિષ્ણાત',
      booked: 'બુક કરેલ',
      en_route: 'રસ્તામાં',
      service: 'સેવા',
      service_completed: 'સેવા પૂર્ણ થઈ',
      delivered: 'ડિલિવર કરેલ',
      no_active_orders: 'કોઈ સક્રિય ઓર્ડર નથી',
      no_active_orders_sub: "તમારી પાસે અત્યારે કોઈ સક્રિય ડિલિવરી નથી.",
      active_ride_bookings: 'સક્રિય સવારી બુકિંગ',
      confirmed: 'કન્ફર્મ',
      seats: 'સીટો',
      driver_live: 'ડ્રાઇવર લાઇવ',
      awaiting_driver: 'ડ્રાઇવરની રાહ જોવાઈ રહી છે',
      driver_en_route: 'ડ્રાઇવર રસ્તામાં છે',
      preparing_ride: 'સવારી તૈયાર થઈ રહી છે',
      ride_confirmed_board: 'સવારી કન્ફર્મ થઈ — પિકઅપ પોઇન્ટ પર બોર્ડ કરો',
      show_qr_code_driver: 'ડ્રાઇવરને ક્યૂઆર કોડ બતાવો. સીટ રિઝર્વ થઈ.',
      view_ticket: 'ટિકિટ જુઓ',
      my_event_tickets: 'મારી ઇવેન્ટ ટિકિટ',
      previous_orders: 'ભૂતકાળના ઓર્ડર',
      rate: 'રેટ કરો',
      rated: 'રેટેડ',
      fulfilled: 'પૂર્ણ',
      cancelled: 'રદ કરેલ',
      no_history_available: 'હજી સુધી કોઈ ઇતિહાસ ઉપલબ્ધ નથી.',
      cancel_order_confirm_title: 'ઓર્ડર રદ કરવો છે?',
      cancel_order_confirm_desc: 'શું તમે ખરેખર આ ઓર્ડર રદ કરવા માંગો છો? આ ક્રિયા પાછી ખેંચી શકાશે નહીં.',
      no_keep_it: 'ના, રહેવા દો',
      yes_cancel: 'હા, રદ કરો',
      order_details: 'ઓર્ડરની વિગતો',
      invoice: 'ઇનવોઇસ',
      service_address: 'સેવા સરનામું',
      items_summary: 'આઇટમ્સ સારાંશ',
      details_not_available: 'વિગતો ઉપલબ્ધ નથી',
      total_refunded_paytm: 'કુલ રિફંડ (Paytm)',
      total_paid: 'કુલ ચુકવણી',
      payment_info: 'ચુકવણી માહિતી',
      refunded_to_paytm: 'Paytm માં રિફંડ મળ્યું',
      paid_online: 'ઓનલાઇન ચૂકવેલ',
      transaction_id: 'ટ્રાન્ઝેક્શન આઈડી',
      refunded: 'રિફંડ મળ્યું',
      success: 'સફળ',
      rate_your_experience: 'તમારા અનુભવને રેટ કરો',
      your_rating: 'તમારી રેટિંગ',
      already_rated_msg: 'તમે આ ઓર્ડર માટે પહેલેથી જ પ્રતિસાદ સબમિટ કર્યો છે. આભાર!',
      help_improve_service: 'અમારી સેવા સુધારવામાં મદદ કરો',
      rate_now: 'અત્યારે રેટ કરો',
      rate_order_title: 'ઓર્ડર રેટ કરો',
      tell_us_more: 'અમને વધુ કહો (વૈકલ્પિક)...',
      select_rating_above: 'ઉપર રેટિંગ પસંદ કરો',
      submitting: 'સબમિટ થઈ રહ્યું છે...',
      submit_rating_btn: 'રેટિંગ સબમિટ કરો',
      feedback_goes_to_store: 'તમારો પ્રતિસાદ સીધો સ્ટોર પર જાય છે',
      coming_soon: 'ટૂંક સમયમાં',
      rating_1: 'ખૂબ ખરાબ 😞',
      rating_2: 'સારું નથી 😕',
      rating_3: 'બરાબર 🙂',
      rating_4: 'ખૂબ સારું 😊',
      rating_5: 'ઉત્કૃષ્ટ! 🤩',
      events_near_you: 'તમારી નજીકના કાર્યક્રમો',
      upcoming: 'આગામી',
      past: 'ભૂતકાળના',
      search_events_placeholder: 'ઇવેન્ટ્સ, સંગીત કાર્યક્રમો, વર્કશોપ શોધો...',
      all_show_types: 'બધા શો પ્રકાર',
      single_show: 'સિંગલ શો',
      multiple_shows: 'મલ્ટીપલ શો',
      tour_festival: 'ટૂર / ફેસ્ટિવલ',
      events_found: 'ઇવેન્ટ્સ મળી',
      event_found: 'ઇવેન્ટ મળી',
      loading_events: 'ઇવેન્ટ્સ લોડ થઈ રહી છે...',
      no_events_found: 'કોઈ {filter} ઇવેન્ટ્સ મળી નથી',
      show_all_events: 'બધા કાર્યક્રમો બતાવો',
      sold_out: 'હાજર નથી',
      onwards: 'થી શરૂ',
      only_n_left: 'ફક્ત {n} બાકી છે!',
      n_available: '{n} ઉપલબ્ધ',
      prev: 'પાછળ',
      next: 'આગળ',
      cat_all: 'બધા',
      cat_music_concerts: 'સંગીત અને કોન્સર્ટ',
      cat_comedy_theatre: 'કોમેડી અને થિયેટર',
      cat_workshops_classes: 'વર્કશોપ અને વર્ગો',
      cat_parties_nightlife: 'પાર્ટી અને નાઇટલાઇફ',
      cat_festivals_fairs: 'તહેવારો અને મેળાઓ',
      cat_sports_fitness: 'રમતગમત અને ફિટનેસ',
      cat_corporate_business: 'કોર્પોરેટ અને વ્યવસાય'
    }
  },
  mr: {
    name: 'मराठी',
    dir: 'ltr',
    translations: {
      welcome: 'पासवाला मध्ये आपले स्वागत आहे',
      tagline: 'तुमचे विश्वसनीय शेजारी केंद्र',
      near_shops: 'जवळपासची दुकाने',
      expert_services: 'स्थानिक तज्ज्ञ',
      community: 'समुदाय',
      essentials: 'दैनंदिन गरजा',
      search_placeholder: 'दुकाने किंवा सेवा शोधा...',
      add_to_cart: 'कार्टमध्ये जोडा',
      book_now: 'आता बुक करा',
      checkout: 'चेकआउट',
      cart_empty: 'तुमची कार्ट रिकामी आहे',
      savings: 'तुम्ही वाचवले',
      vendor_mode: 'विक्रेता मोडवर स्विच करा',
      profile: 'प्रोफाइल',
      logout: 'साइन आउट',
      location: 'वर्तमान स्थान',
      change_location: 'स्थान बदला',
      trust_badge: '{n} शेजार्‍यांचा विश्वास',
      new_order: 'नवीन ऑर्डर',
      total: 'एकूण',
      items: 'वस्तू',
      ai_expert: 'AI तज्ज्ञांशी चॅट करा',
      
      // Profile Page Translations
      appearance: 'देखावा',
      dark_mode: 'डार्क मोड',
      switch_theme: 'थीम शैली बदला',
      account_activity: 'खाते आणि क्रियाकलाप',
      order_history: 'ऑर्डर इतिहास',
      view_past_bookings: 'तुमचे मागील बुकिंग पहा',
      passwala_wallet: 'पासवाला वॉलेट',
      manage_credits: 'तुमचे क्रेडिट व्यवस्थापित करा',
      delivery_address: 'वितरणाचा पत्ता',
      manage_locations: 'तुमची ठिकाणे व्यवस्थापित करा',
      data_safety_deletion: 'डेटा सुरक्षा आणि हटवणे',
      manage_data_rights: 'तुमचे डेटा अधिकार व्यवस्थापित करा',
      privacy_security: 'गोपनीयता आणि सुरक्षा',
      manage_security: 'तुमची सुरक्षा व्यवस्थापित करा',
      help_support: 'मदत आणि समर्थन',
      support_24_7: '24/7 समर्थन उपलब्ध',
      settings: 'सेटिंग्ज',
      app_preferences: 'अॅप प्राधान्ये',
      logout_session: 'तुमच्या सत्रातून लॉगआउट करा',
      delete_account_permanently: 'खाते कायमचे हटवा',
      
      // Hub Translations
      verified_pros: 'प्रमाणित स्थानिक व्यावसायिक',
      best_stores: 'सर्वोत्तम शेजारची दुकाने',
      city_rides: 'शहर सवारी',
      city_rides_sub: 'अहमदाबाद ट्रान्झिट',
      event_tickets: 'इव्हेंट तिकिटे',
      event_tickets_sub: 'अहमदाबाद कार्यक्रम',
      join_floor_chat: 'चॅटमध्ये सामील व्हा',
      book_pro: 'प्रो बुक करा',
      book_now_caps: 'आता बुक करा',
      book_ticket: 'तिकीट बुक करा',
      
      // Near Shops / Experts Translations
      search_shops_items: 'दुकाने, वस्तू शोधा...',
      search_experts_services: 'तज्ज्ञ, सेवा शोधा...',
      all: 'सर्व',
      general_store: 'जनरल स्टोअर',
      grocery: 'किराणा',
      vegetables: 'भाज्या',
      dairy: 'डेअरी',
      bakery: 'बेकरी',
      plumbing: 'प्लंबिंग',
      electrical: 'इलेक्ट्रिकल',
      ac_service: 'एसी सर्व्हिस',
      cleaning: 'सफाई',
      carpentry: 'सुतारकाम',
      ac_appliance: 'एसी आणि उपकरणे',
      painting: 'पेंटिंग',
      grocery_essentials: 'किराणा आणि जीवनावश्यक वस्तू',
      fruits_vegetables: 'फळे आणि भाज्या',
      dairy_bread_eggs: 'डेअरी, ब्रेड आणि अंडी',
      beverages_munchies: 'पेये आणि फराळ',
      personal_care_hygiene: 'वैयक्तिक काळजी आणि स्वच्छता',
      household_pet_care: 'घरगुती आणि पाळीव प्राण्यांची काळजी',
      plumbing_services: 'प्लंबिंग सेवा',
      electrical_services: 'इलेक्ट्रिकल सेवा',
      home_cleaning_deep_clean: 'घरची स्वच्छता आणि खोल स्वच्छता',
      ac_appliance_repair: 'एसी आणि उपकरण दुरुस्ती',
      pest_control_services: 'कीटक नियंत्रण सेवा',
      home_painting_decor: 'घरचे रंगकाम आणि सजावट',
      describe_issue: 'समस्येचे वर्णन करा (जसे की नळ गळणे, एसी सेवा)...',
      inspection_fee: 'तपासणी शुल्क',
      km_away: '{dist} किमी दूर',
      you_are_here: 'तुम्ही इथे आहात',
      view_services: 'सेवा पहा',
      view_catalog: 'कॅटलॉग पहा',
      book_expert: 'तज्ज्ञ बुक करा',
      pickup_location: 'पिकअप ठिकाण',
      dropoff_location: 'ड्रॉप-ऑफ ठिकाण',
      search_pickup_placeholder: 'पिकअप ठिकाण शोधा किंवा नकाशावर टॅप करा...',
      search_dropoff_placeholder: 'ड्रॉप-ऑफ ठिकाण शोधा किंवा नकाशावर टॅप करा...',
      popular_areas: 'अहमदाबादमधील लोकप्रिय भाग',
      search_available_rides: 'उपलब्ध वाहने शोधा',
      confirm_ride: 'सवारीची पुष्टी करा',
      route_details: 'मार्ग तपशील',
      available_vehicle: 'उपलब्ध वाहन',
      luggage_options: 'सामान / पॅकेजचे वजन (पर्यायी)',
      luggage_weight: 'सामान वजन: {w} किलो',
      gst_tax: 'जीएसटी (5%)',
      total_fare: 'एकूण भाडे',
      book_ticket_btn: 'तिकीट बुक करा',
      back_to_search: 'शोध वर परत जा',
      distance_unknown: 'अंतर माहीत नाही',
      km_from_you: 'तुमच्यापासून {dist} किमी',
      no_shops_found: 'कोणतीही जुळणारी दुकाने आढळली नाहीत',
      no_shops_found_sub: 'तुमच्या भागातील वेगळी श्रेणी किंवा स्टोअरचे नाव शोधण्याचा प्रयत्न करा.',
      service_portfolio: 'सेवा पोर्टफोलिओ',
      digital_catalog: 'डिजिटल कॅटलॉग',
      available_services: 'उपलब्ध सेवा',
      available_products: 'उपलब्ध उत्पादने',
      out_of_stock: 'आउट ऑफ स्टॉक',
      no_services_available: 'सध्या कोणत्याही सेवा उपलब्ध नाहीत.',
      no_products_available: 'सध्या कोणतीही उत्पादने उपलब्ध नाहीत.',
      wallet_balance_title: 'उपलब्ध शिल्लक',
      add_money: 'पैसे जोडा',
      send_money: 'पैसे पाठवा',
      rewards: 'पुरस्कार',
      recent_transactions: 'अलीकडील व्यवहार',
      see_all: 'सर्व पहा',
      rbi_sandbox_title: 'पासवाला वॉलेट बीटा (RBI सँडबॉक्स)',
      rbi_sandbox_desc: 'पीअर वॉलेट शिल्लक आणि व्यवहार वैशिष्ट्ये सध्या सँडबॉक्स नियामक ऑडिटच्या अंतर्गत मॉक/डेमो मोडमध्ये चालू आहेत.',
      bank_grade_encryption: 'बँक-ग्रेड एन्क्रिप्शन',
      bank_grade_encryption_sub: 'पासवाला ट्रस्ट शिल्डसह आपले व्यवहार 100% सुरक्षित आहेत.',
      top_questions: 'शीर्ष प्रश्न',
      still_need_help: 'अजूनही मदत हवी आहे का?',
      whatsapp_support: 'व्हाट्सएप मदत',
      whatsapp_support_sub: '5 मिनिटांत त्वरित उत्तर',
      email_support: 'ईमेल मदत',
      email_support_sub: 'आम्ही 24 तासांच्या आत उत्तर देतो',
      call_support: 'कॉल मदत',
      call_support_sub: 'सोम - शनि, सकाळी 10 - संध्याकाळी 7',
      app_version: 'अॅप आवृत्ती 2.0.4 प्रीमियम',
      account_security: 'खाते सुरक्षा',
      high: 'उच्च',
      medium: 'मध्यम',
      low: 'कमी',
      security_fully_secured: 'तुमचे खाते पूर्णपणे सुरक्षित आहे.',
      security_medium_tip: 'उच्च सुरक्षा पातळीवर पोहोचण्यासाठी अॅप लॉक सुरू करा.',
      security_low_tip: 'तुमचे खाते सुरक्षित करण्यासाठी 2FA आणि अॅप लॉक सुरू करा.',
      security_controls: 'सुरक्षा नियंत्रणे',
      two_factor: 'दोन-घटक प्रमाणीकरण',
      two_factor_sub: 'खाते सुरक्षेसाठी 2FA सुरू करा',
      app_lock: 'अॅप लॉक',
      app_lock_sub: 'बायोमेट्रिक लॉकसह अॅप सुरक्षित करा',
      privacy_policy_title: 'गोपनीयता धोरण',
      privacy_policy_sub: 'आमचे डेटा वापर धोरण वाचा',
      data_management: 'डेटा व्यवस्थापन',
      data_management_sub: 'तुमचा डेटा निर्यात किंवा व्यवस्थापित करा',
      encryption_note: 'पासवालाशी तुमचे कनेक्शन 256-बिट SSL तंत्रज्ञानाने एन्क्रिप्ट केलेले आहे. सत्यापित ऑर्डर्सशिवाय तुमचे रिअल-टाइम खाजगी स्थान कोणीही, अगदी पासवाला देखील पाहू शकत नाही.',
      rate_order: 'तुमच्या ऑर्डरला रेट करा',
      order_no: 'ऑर्डर',
      rate_order_cta: 'ऑर्डर रेट करा',
      rated_badge: 'रेट केलेले',
      write_review: 'तुमचे मत लिहा...',
      submit_rating: 'सबमिट करा',
      order_history_title: 'ऑर्डर इतिहास',
      verified_agent: 'प्रमाणित एजंट',
      active_orders: 'सक्रिय ऑर्डर',
      more: 'आणि',
      delivery_location: 'वितरण ठिकाण',
      service_location: 'सेवा ठिकाण',
      partner: 'भागीदार',
      service_expert: 'सेवा तज्ज्ञ',
      booked: 'बुक केले',
      en_route: 'मार्गावर',
      service: 'सेवा',
      service_completed: 'सेवा पूर्ण झाली',
      delivered: 'वितरित',
      no_active_orders: 'कोणतीही सक्रिय ऑर्डर नाही',
      no_active_orders_sub: "तुमच्याकडे सध्या कोणतीही सक्रिय वितरणे नाहीत.",
      active_ride_bookings: 'सक्रिय सवारी बुकिंग',
      confirmed: 'पुष्टी केली',
      seats: 'सीट',
      driver_live: 'ड्रायव्हर लाइव्ह',
      awaiting_driver: 'ड्रायव्हरची प्रतीक्षा',
      driver_en_route: 'ड्रायव्हर मार्गावर आहे',
      preparing_ride: 'सवारी तयार केली जात आहे',
      ride_confirmed_board: 'सवारीची पुष्टी — पिकअप पॉइंटवर चढा',
      show_qr_code_driver: 'ड्रायव्हरला क्यूआर कोड दाखवा. सीट राखीव.',
      view_ticket: 'तिकीट पहा',
      my_event_tickets: 'माझी इव्हेंट तिकिटे',
      previous_orders: 'मागील ऑर्डर्स',
      rate: 'रेट करा',
      rated: 'रेट केले',
      fulfilled: 'पूर्ण',
      cancelled: 'रद्द केले',
      no_history_available: 'अद्याप इतिहास उपलब्ध नाही.',
      cancel_order_confirm_title: 'ऑर्डर रद्द करायची?',
      cancel_order_confirm_desc: 'तुम्हाला खात्री आहे की तुम्ही ही ऑर्डर रद्द करू इच्छिता? ही क्रिया पूर्ववत केली जाऊ शकत नाही.',
      no_keep_it: 'नाही, ठेवा',
      yes_cancel: 'होय, रद्द करा',
      order_details: 'ऑर्डर तपशील',
      invoice: 'इनव्हॉइस',
      service_address: 'सेवा पत्ता',
      items_summary: 'वस्तूंचा सारांश',
      details_not_available: 'तपशील उपलब्ध नाही',
      total_refunded_paytm: 'एकूण परतावा (Paytm)',
      total_paid: 'एकूण भरले',
      payment_info: 'पेमेंट माहिती',
      refunded_to_paytm: 'Paytm वर परत केले',
      paid_online: 'ऑनलाइन भरले',
      transaction_id: 'व्यवहार आयडी',
      refunded: 'परतावा दिला',
      success: 'यशस्वी',
      rate_your_experience: 'तुमचा अनुभव रेट करा',
      your_rating: 'तुमचे रेटिंग',
      already_rated_msg: 'तुमचे रेटिंग आधीच सबमिट केले आहे.',
      help_improve_service: 'आम्हाला आमची सेवा सुधारण्यात मदत करा',
      rate_now: 'आता रेट करा',
      rate_order_title: 'ऑर्डर रेट करा',
      tell_us_more: 'आम्हाला अधिक सांगा (पर्यायी)...',
      select_rating_above: 'वर रेटिंग निवडा',
      submitting: 'सबमिट करत आहे...',
      submit_rating_btn: 'रेटिंग सबमिट करा',
      feedback_goes_to_store: 'तुमचा अभिप्राय थेट स्टोअरकडे जातो',
      coming_soon: 'लवकरच येत आहे',
      rating_1: 'खूप वाईट 😞',
      rating_2: 'चांगले नाही 😕',
      rating_3: 'ठीक आहे 🙂',
      rating_4: 'खूप चांगले 😊',
      rating_5: 'उत्कृष्ट! 🤩',
      events_near_you: 'तुमच्या जवळील कार्यक्रम',
      upcoming: 'आगामी',
      past: 'मागील',
      search_events_placeholder: 'कार्यक्रम, संगीत मैफिली, कार्यशाळा शोधा...',
      all_show_types: 'सर्व शो प्रकार',
      single_show: 'एकल शो',
      multiple_shows: 'एकाधिक शो',
      tour_festival: 'टूर / उत्सव',
      events_found: 'कार्यक्रम सापडले',
      event_found: 'कार्यक्रम सापडला',
      loading_events: 'कार्यक्रम लोड होत आहेत...',
      no_events_found: 'कोणतेही {filter} कार्यक्रम सापडले नाहीत',
      show_all_events: 'सर्व कार्यक्रम दाखवा',
      sold_out: 'पूर्ण विकले',
      onwards: 'पासून',
      only_n_left: 'फक्त {n} शिल्लक!',
      n_available: '{n} उपलब्ध',
      prev: 'मागे',
      next: 'पुढे',
      cat_all: 'सर्व',
      cat_music_concerts: 'संगीत आणि मैफिली',
      cat_comedy_theatre: 'कॉमेडी आणि थिएटर',
      cat_workshops_classes: 'कार्यशाळा आणि वर्ग',
      cat_parties_nightlife: 'पार्टी आणि नाईटलाईफ',
      cat_festivals_fairs: 'उत्सव आणि मेळे',
      cat_sports_fitness: 'क्रीडा आणि फिटनेस',
      cat_corporate_business: 'कॉर्पोरेट आणि व्यवसाय'
    }
  },
  ta: {
    name: 'தமிழ்',
    dir: 'ltr',
    translations: {
      welcome: 'பாஸ்வாலாவிற்கு வரவேற்கிறோம்',
      tagline: 'உங்கள் நம்பகமான அண்டை மையம்',
      near_shops: 'அருகிலுள்ள கடைகள்',
      expert_services: 'உள்ளூர் நிபுணர்கள்',
      community: 'சமூகம்',
      essentials: 'தினசரி தேவைகள்',
      search_placeholder: 'கடைகள் அல்லது சேவைகளைத் தேடுங்கள்...',
      add_to_cart: 'கார்ட்டில் சேர்',
      book_now: 'இப்போது முன்பதிவு செய்',
      checkout: 'செக் அவுட்',
      cart_empty: 'உங்கள் கார்ட் காலியாக உள்ளது',
      savings: 'நீங்கள் சேமித்தது',
      vendor_mode: 'விற்பனையாளர் பயன்முறைக்கு மாறவும்',
      profile: 'சுயவிவரம்',
      logout: 'வெளியேறு',
      location: 'தற்போதைய இடம்',
      change_location: 'இருப்பிடத்தை மாற்றவும்',
      trust_badge: '{n} அண்டை வீட்டார்களால் நம்பப்படுகிறது',
      new_order: 'புதிய ஆர்டர்',
      total: 'மொத்தம்',
      items: 'பொருட்கள்',
      ai_expert: 'AI நிபுணருடன் அரட்டையடிக்கவும்',
      
      // Profile Page Translations
      appearance: 'தோற்றம்',
      dark_mode: 'இருண்ட பயன்முறை',
      switch_theme: 'தீம் பாணியை மாற்றவும்',
      account_activity: 'கணக்கு & செயல்பாடு',
      order_history: 'ஆர்டர் வரலாறு',
      view_past_bookings: 'உங்கள் கடந்தகால முன்பதிவுகளைப் பார்க்கவும்',
      passwala_wallet: 'பாஸ்வாலா வாலட்',
      manage_credits: 'உங்கள் வரம்புகளை நிர்வகிக்கவும்',
      delivery_address: 'டெலிவரி முகவரி',
      manage_locations: 'உங்கள் இருப்பிடங்களை நிர்வகிக்கவும்',
      data_safety_deletion: 'தரவு பாதுகாப்பு & நீக்கம்',
      manage_data_rights: 'உங்கள் தரவு உரிமைகளை நிர்வகிக்கவும்',
      privacy_security: 'தனியுரிமை & பாதுகாப்பு',
      manage_security: 'உங்கள் பாதுகாப்பை நிர்வகிக்கவும்',
      help_support: 'உதவி & ஆதரவு',
      support_24_7: '24/7 ஆதரவு கிடைக்கும்',
      settings: 'அமைப்புகள்',
      app_preferences: 'பயன்பாட்டு விருப்பத்தேர்வுகள்',
      logout_session: 'உங்கள் அமர்விலிருந்து வெளியேறவும்',
      delete_account_permanently: 'கணக்கை நிரந்தரமாக நீக்கு',
      
      // Hub Translations
      verified_pros: 'சரிபார்க்கப்பட்ட உள்ளூர் வல்லுநர்கள்',
      best_stores: 'சிறந்த அண்டை கடைகள்',
      city_rides: 'நகர சவாரிகள்',
      city_rides_sub: 'அகமதாபாத் போக்குவரத்து',
      event_tickets: 'நிகழ்ச்சி டிக்கெட்டுகள்',
      event_tickets_sub: 'அகமதாபாத் நிகழ்வுகள்',
      join_floor_chat: 'அரட்டையில் இணையுங்கள்',
      book_pro: 'நிபுணரை பதிவு செய்',
      order_now: 'இப்போது ஆர்டர் செய்',
      book_ticket: 'டிக்கெட் முன்பதிவு செய்',
      book_now_caps: 'இப்போது முன்பதிவு செய்',
      
      // Near Shops / Experts Translations
      search_shops_items: 'கடைகள், பொருட்களைத் தேடுங்கள்...',
      search_experts_services: 'நிபுணர்கள், சேவைகளைத் தேடுங்கள்...',
      all: 'அனைத்தும்',
      general_store: 'பொது அங்காடி',
      grocery: 'மளிகை',
      vegetables: 'காய்கறிகள்',
      dairy: 'பால் பண்ணை',
      bakery: 'பேக்கரி',
      plumbing: 'குழாய் வேலை',
      electrical: 'மின்சாரம்',
      ac_service: 'ஏசி சேவை',
      cleaning: 'சுத்தம் செய்தல்',
      carpentry: 'தச்சு வேலை',
      ac_appliance: 'ஏசி & உபகரணங்கள்',
      painting: 'பெயிண்டிங்',
      grocery_essentials: 'மளிகை மற்றும் அத்தியாவசிய பொருட்கள்',
      fruits_vegetables: 'பழங்கள் மற்றும் காய்கறிகள்',
      dairy_bread_eggs: 'பால் பண்ணை, ரொட்டி & முட்டை',
      beverages_munchies: 'பானங்கள் மற்றும் நொறுக்குத்தீனிகள்',
      personal_care_hygiene: 'தனிநபர் பராமரிப்பு & சுகாதாரம்',
      household_pet_care: 'வீட்டு உபயோகம் & செல்லப்பிராணி பராமரிப்பு',
      plumbing_services: 'குழாய் சேவைகள்',
      electrical_services: 'மின்சார சேவைகள்',
      home_cleaning_deep_clean: 'வீடு சுத்தம் மற்றும் ஆழமான சுத்தம்',
      ac_appliance_repair: 'ஏசி மற்றும் உபகரணங்கள் பழுதுபார்ப்பு',
      pest_control_services: 'பூச்சி கட்டுப்பாடு சேவைகள்',
      home_painting_decor: 'வீட்டு வண்ணம் மற்றும் அலங்காரம்',
      describe_issue: 'சிக்கலை விவரிக்கவும் (எ.கா. குழாய் கசிவு, ஏசி சேவை)...',
      inspection_fee: 'ஆய்வு கட்டணம்',
      km_away: '{dist} கிமீ தொலைவில்',
      you_are_here: 'நீங்கள் இங்கே இருக்கிறீர்கள்',
      view_services: 'சேவைகளைப் பார்க்கவும்',
      view_catalog: 'பட்டியலைப் பார்க்கவும்',
      book_expert: 'நிபுணரை பதிவு செய்',
      pickup_location: 'பிக்கப் இருப்பிடம்',
      dropoff_location: 'டிராப் இருப்பிடம்',
      search_pickup_placeholder: 'பிக்கப் இடத்தை தேடவும் அல்லது வரைபடத்தில் தட்டவும்...',
      search_dropoff_placeholder: 'டிராப் இடத்தை தேடவும் அல்லது வரைபடத்தில் தட்டவும்...',
      popular_areas: 'அகமதாபாத்தில் பிரபலமான பகுதிகள்',
      search_available_rides: 'கிடைக்கக்கூடிய சவாரிகளைத் தேடுங்கள்',
      confirm_ride: 'சவாரியை உறுதிப்படுத்துக',
      route_details: 'பயண வழி விவரங்கள்',
      available_vehicle: 'கிடைக்கக்கூடிய வாகனம்',
      luggage_options: 'லக்கேஜ் / பார்சல் எடை (விருப்பம்)',
      luggage_weight: 'லக்கேஜ் எடை: {w} கிலோ',
      gst_tax: 'ஜிஎஸ்டி (5%)',
      total_fare: 'மொத்த கட்டணம்',
      book_ticket_btn: 'டிக்கெட் பதிவு செய்',
      back_to_search: 'தேடலுக்குத் திரும்பு',
      distance_unknown: 'தொலைவு தெரியவில்லை',
      km_from_you: 'உங்களிடமிருந்து {dist} கிமீ',
      no_shops_found: 'பொருந்தும் கடைகள் எதுவும் இல்லை',
      no_shops_found_sub: 'உங்கள் பகுதியில் வேறு வகை அல்லது கடையின் பெயரைத் தேட முயற்சிக்கவும்.',
      service_portfolio: 'சேவை போர்ட்ஃபோலியோ',
      digital_catalog: 'டிஜிட்டல் பட்டியல்',
      available_services: 'கிடைக்கக்கூடிய சேவைகள்',
      available_products: 'கிடைக்கக்கூடிய தயாரிப்புகள்',
      out_of_stock: 'ஸ்டாக் இல்லை',
      no_services_available: 'தற்போது சேவைகள் எதுவும் இல்லை.',
      no_products_available: 'தற்போது தயாரிப்புகள் எதுவும் இல்லை.',
      wallet_balance_title: 'கிடைக்கக்கூடிய இருப்பு',
      add_money: 'பணம் சேர்',
      send_money: 'பணம் அனுப்பு',
      rewards: 'பரிசுகள்',
      recent_transactions: 'சமீபத்திய பரிவர்த்தனைகள்',
      see_all: 'அனைத்தையும் பார்',
      rbi_sandbox_title: 'பாஸ்வாலா வாலட் பீட்டா (ஆர்பிஐ சாண்ட்பாக்ஸ்)',
      rbi_sandbox_desc: 'பியர் வாலட் இருப்புகள் மற்றும் பரிவர்த்தனை அம்சங்கள் தற்போது சாண்ட்பாக்ஸ் ஒழுங்குமுறை தணிக்கைகளுக்கு உட்பட்டு மாதிரி/டெமோ பயன்முறையில் இயங்குகின்றன.',
      bank_grade_encryption: 'வங்கி-தர குறியாக்கம்',
      bank_grade_encryption_sub: 'பாஸ்வாலா டிரஸ்ட் ஷீல்டு மூலம் உங்கள் பரிவர்த்தனைகள் 100% பாதுகாப்பானவை.',
      top_questions: 'முக்கிய கேள்விகள்',
      still_need_help: 'இன்னும் உதவி தேவையா?',
      whatsapp_support: 'வாட்ஸ்அப் ஆதரவு',
      whatsapp_support_sub: '5 நிமிடங்களுக்குள் உடனடி பதில்',
      email_support: 'மின்னஞ்சல் ஆதரவு',
      email_support_sub: 'நாங்கள் 24 மணி நேரத்திற்குள் பதிலளிக்கிறோம்',
      call_support: 'அழைப்பு ஆதரவு',
      call_support_sub: 'திங்கள் - சனி, காலை 10 - மாலை 7 மணி',
      app_version: 'பயன்பாட்டு பதிப்பு 2.0.4 பிரீமியம்',
      account_security: 'கணக்கு பாதுகாப்பு',
      high: 'அதிகம்',
      medium: 'நடுத்தரம்',
      low: 'குறைவு',
      security_fully_secured: 'உங்கள் கணக்கு முழுமையாக பாதுகாக்கப்பட்டுள்ளது.',
      security_medium_tip: 'உயர் பாதுகாப்பு நிலையை அடைய ஆப் லாக்கை இயக்கவும்.',
      security_low_tip: 'உங்கள் கணக்கைப் பாதுகாக்க 2FA மற்றும் ஆப் லாக்கை இயக்கவும்.',
      security_controls: 'பாதுகாப்பு கட்டுப்பாடுகள்',
      two_factor: 'இரண்டு காரணி அங்கீகாரம்',
      two_factor_sub: 'கணக்கு பாதுகாப்பிற்காக 2FA ஐ இயக்கவும்',
      app_lock: 'ஆப் லாக்',
      app_lock_sub: 'பயோமெட்ரிக் பூட்டுடன் பயன்பாட்டைப் பாதுகாக்கவும்',
      privacy_policy_title: 'தனியுரிமைக் கொள்கை',
      privacy_policy_sub: 'எங்கள் தரவு பயன்பாட்டுக் கொள்கையைப் படியுங்கள்',
      data_management: 'தரவு மேலாண்மை',
      data_management_sub: 'உங்கள் தரவை ஏற்றுமதி அல்லது நிர்வகிக்கவும்',
      encryption_note: 'பாஸ்வாலாவிற்கான உங்கள் இணைப்பு 256-பிட் SSL தொழில்நுட்பத்துடன் குறியாக்கம் செய்யப்பட்டுள்ளது. சரிபார்க்கப்பட்ட ஆர்டர்களைத் தவிர வேறு யாரும், பாஸ்வாலா கூட, உங்கள் நிகழ்நேர தனிப்பட்ட இருப்பிடத்தைக் காண முடியாது.',
      rate_order: 'உங்கள் ஆர்டரை மதிப்பிடவும்',
      order_no: 'ஆர்டர்',
      rate_order_cta: 'ஆர்டரை மதிப்பிடவும்',
      rated_badge: 'மதிப்பிடப்பட்டது',
      write_review: 'உங்கள் மதிப்பாய்வை எழுதவும்...',
      submit_rating: 'சமர்ப்பிக்கவும்',
      order_history_title: 'ஆர்டர் வரலாறு',
      verified_agent: 'சரிபார்க்கப்பட்ட முகவர்',
      active_orders: 'செயலில் உள்ள ஆர்டர்கள்',
      more: 'மேலும்',
      delivery_location: 'டெலிவரி இருப்பிடம்',
      service_location: 'சேவை இருப்பிடம்',
      partner: 'பங்குதாரர்',
      service_expert: 'சேவை நிபுணர்',
      booked: 'முன்பதிவு செய்யப்பட்டது',
      en_route: 'வழியில்',
      service: 'சேவை',
      service_completed: 'சேவை முடிந்தது',
      delivered: 'டெலிவரி செய்யப்பட்டது',
      no_active_orders: 'செயலில் உள்ள ஆர்டர்கள் இல்லை',
      no_active_orders_sub: "தற்போது உங்களுக்கு செயலில் உள்ள டெலிவரிகள் எதுவும் இல்லை.",
      active_ride_bookings: 'செயலில் உள்ள சவாரி முன்பதிவுகள்',
      confirmed: 'உறுதி செய்யப்பட்டது',
      seats: 'இருக்கைகள்',
      driver_live: 'டிரைவர் லைவ்',
      awaiting_driver: 'டிரைவருக்காக காத்திருக்கிறது',
      driver_en_route: 'டிரைவர் வழியில் உள்ளார்',
      preparing_ride: 'சவாரி தயார் செய்யப்படுகிறது',
      ride_confirmed_board: 'சவாரி உறுதி செய்யப்பட்டது — பிக்கப் பாயிண்டில் ஏறவும்',
      show_qr_code_driver: 'டிரைவரிடம் இந்த க்யூஆர் குறியீட்டைக் காட்டுங்கள். இருக்கை(கள்) முன்பதிவு செய்யப்பட்டது.',
      view_ticket: 'டிக்கெட் பார்',
      my_event_tickets: 'எனது நிகழ்ச்சி டிக்கெட்டுகள்',
      previous_orders: 'முந்தைய ஆர்டர்கள்',
      rate: 'மதிப்பிடு',
      rated: 'மதிப்பிடப்பட்டது',
      fulfilled: 'நிறेவேற்றப்பட்டது',
      cancelled: 'ரத்து செய்யப்பட்டது',
      no_history_available: 'இன்னும் வரலாறு கிடைக்கவில்லை.',
      cancel_order_confirm_title: 'ஆர்டரை ரத்து செய்யவா?',
      cancel_order_confirm_desc: 'இந்த ஆர்டரை ரத்து செய்ய விரும்புகிறீர்களா? இந்த செயலை மாற்ற முடியாது.',
      no_keep_it: 'இல்லை, வைத்திருக்கவும்',
      yes_cancel: 'ஆம், ரத்துசெய்',
      order_details: 'ஆர்டர் விவரங்கள்',
      invoice: 'இன்வாய்ஸ்',
      service_address: 'சேவை முகவரி',
      items_summary: 'பொருட்கள் சுருக்கம்',
      details_not_available: 'விவரங்கள் கிடைக்கவில்லை',
      total_refunded_paytm: 'மொத்த திரும்பப் பெறப்பட்ட தொகை (Paytm)',
      total_paid: 'மொத்த செலுத்தப்பட்ட தொகை',
      payment_info: 'கட்டண விவரம்',
      refunded_to_paytm: 'Paytm கணக்கிற்கு திரும்ப அனுப்பப்பட்டது',
      paid_online: 'ஆன்லைனில் செலுத்தப்பட்டது',
      transaction_id: 'பரிவர்த்தனை ஐடி',
      refunded: 'திரும்பப் பெறப்பட்டது',
      success: 'வெற்றி',
      rate_your_experience: 'உங்கள் அனுபவத்தை மதிப்பிடுங்கள்',
      your_rating: 'உங்கள் மதிப்பீடு',
      already_rated_msg: 'இந்த ஆர்டருக்கான கருத்துக்களை நீங்கள் ஏற்கனவே சமர்ப்பித்துள்ளீர்கள். நன்றி!',
      help_improve_service: 'எங்கள் சேவையை மேம்படுத்த உதவுங்கள்',
      rate_now: 'இப்போது மதிப்பிடு',
      rate_order_title: 'ஆர்டரை மதிப்பிடு',
      tell_us_more: 'மேலும் விவரங்கள் (விருப்பம்)...',
      select_rating_above: 'மேலே ஒரு மதிப்பீட்டைத் தேர்ந்தெடுக்கவும்',
      submitting: 'சமர்ப்பிக்கிறது...',
      submit_rating_btn: 'மதிப்பீட்டைச் சமர்ப்பி',
      feedback_goes_to_store: 'உங்கள் கருத்து நேரடியாக கடைக்குச் செல்லும்',
      coming_soon: 'விரைவில்',
      rating_1: 'மிகவும் மோசம் 😞',
      rating_2: 'நன்றாக இல்லை 😕',
      rating_3: 'பரவாயில்லை 🙂',
      rating_4: 'மிக நன்று 😊',
      rating_5: 'அருமை! 🤩',
      events_near_you: 'உங்களுக்கு அருகிலுள்ள நிகழ்வுகள்',
      upcoming: 'வரவிருக்கும்',
      past: 'கடந்த',
      search_events_placeholder: 'நிகழ்வுகள், இசை நிகழ்ச்சிகள், பட்டறைகளைத் தேடுங்கள்...',
      all_show_types: 'அனைத்து நிகழ்ச்சி வகைகள்',
      single_show: 'ஒற்றை நிகழ்ச்சி',
      multiple_shows: 'பல நிகழ்ச்சிகள்',
      tour_festival: 'சுற்றுப்பயணம் / திருவிழா',
      events_found: 'நிகழ்வுகள் கண்டறியப்பட்டன',
      event_found: 'நிகழ்வு கண்டறியப்பட்டது',
      loading_events: 'நிகழ்வுகள் ஏற்றப்படுகின்றன...',
      no_events_found: 'அத்தகைய {filter} நிகழ்வுகள் எதுவும் இல்லை',
      show_all_events: 'அனைத்து நிகழ்வுகளையும் காட்டு',
      sold_out: 'விற்கப்பட்டது',
      onwards: 'முதல்',
      only_n_left: 'மட்டும் {n} மீதமுள்ளது!',
      n_available: '{n} கிடைக்கும்',
      prev: 'முந்தைய',
      next: 'அடுத்து',
      cat_all: 'அனைத்தும்',
      cat_music_concerts: 'இசை மற்றும் நிகழ்ச்சிகள்',
      cat_comedy_theatre: 'நகைச்சுவை மற்றும் அரங்கம்',
      cat_workshops_classes: 'பட்டறைகள் மற்றும் வகுப்புகள்',
      cat_parties_nightlife: 'பார்ட்டிகள் மற்றும் இரவு வாழ்க்கை',
      cat_festivals_fairs: 'திருவிழாக்கள் மற்றும் கண்காட்சிகள்',
      cat_sports_fitness: 'விளையாட்டு மற்றும் உடற்பயிற்சி',
      cat_corporate_business: 'கார்ப்பரேட் மற்றும் வணிகம்'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('passwala_lang') || 'en';
  });

  const t = (key) => {
    return languages[currentLanguage].translations[key] || languages.en.translations[key] || key;
  };

  const changeLanguage = (lang) => {
    if (languages[lang]) {
      setCurrentLanguage(lang);
      localStorage.setItem('passwala_lang', lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
