/* eslint-disable no-unused-vars, react-refresh/only-export-components */
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const languages = {
  en: {
    name: 'English',
    dir: 'ltr',
    translations: {
      welcome: 'Welcome to Passwala',
      tagline: 'Your Trusted Neighborhood Hub',
      near_shops: 'Near Shops',
      expert_services: 'Local Experts',
      community: 'Community',
      essentials: 'Daily Essentials',
      search_placeholder: 'Search for shops or services...',
      add_to_cart: 'Add to Cart',
      book_now: 'Book Now',
      checkout: 'Checkout',
      cart_empty: 'Your cart is empty',
      savings: 'You saved',
      vendor_mode: 'Switch to Vendor Mode',
      profile: 'Profile',
      logout: 'Sign Out',
      location: 'Current Location',
      change_location: 'Change Location',
      trust_badge: 'Trusted by {n} neighbors',
      new_order: 'New Order',
      total: 'Total',
      items: 'Items',
      ai_expert: 'Chat with AI Expert',
      
      // Profile Page Translations
      appearance: 'Appearance',
      dark_mode: 'Dark Mode',
      switch_theme: 'Switch theme style',
      account_activity: 'Account & Activity',
      order_history: 'Order History',
      view_past_bookings: 'View your past bookings',
      passwala_wallet: 'Passwala Wallet',
      manage_credits: 'Manage your credits',
      delivery_address: 'Delivery Address',
      manage_locations: 'Manage your locations',
      data_safety_deletion: 'Data Safety & Deletion',
      manage_data_rights: 'Manage your data rights',
      privacy_security: 'Privacy & Security',
      manage_security: 'Manage your security',
      help_support: 'Help & Support',
      support_24_7: '24/7 support available',
      settings: 'Settings',
      app_preferences: 'App preferences',
      logout_session: 'Logout of your session',
      delete_account_permanently: 'Delete Account Permanently',
      
      // Hub Translations
      verified_pros: 'Verified local pros',
      best_stores: 'Best neighborhood stores',
      city_rides: 'City Rides',
      city_rides_sub: 'Ahmedabad transit',
      event_tickets: 'Event Tickets',
      event_tickets_sub: 'Ahmedabad events',
      join_floor_chat: 'JOIN FLOOR CHAT',
      book_pro: 'BOOK PRO',
      book_now_caps: 'BOOK NOW',
      book_ticket: 'Book Ticket',
      
      // Near Shops / Experts Translations
      search_shops_items: 'Search shops, items...',
      search_experts_services: 'Search experts, services...',
      all: 'All',
      general_store: 'General Store',
      grocery: 'Grocery',
      vegetables: 'Vegetables',
      dairy: 'Dairy',
      bakery: 'Bakery',
      plumbing: 'Plumbing',
      electrical: 'Electrical',
      ac_service: 'AC Service',
      cleaning: 'Cleaning',
      carpentry: 'Carpentry',
      ac_appliance: 'AC & Appliance',
      painting: 'Painting',
      describe_issue: 'Describe issue (e.g. leaking tap, AC service)...',
      inspection_fee: 'Inspection Fee',
      km_away: '{dist} km away',
      you_are_here: 'You are here',
      view_services: 'View Services',
      view_catalog: 'View Catalog',
      book_expert: 'Book Expert',
      pickup_location: 'PICKUP LOCATION',
      dropoff_location: 'DROP-OFF LOCATION',
      search_pickup_placeholder: 'Search pickup location or tap map...',
      search_dropoff_placeholder: 'Search drop-off location or tap map...',
      popular_areas: 'Popular Areas in Ahmedabad',
      search_available_rides: 'Search Available Rides',
      confirm_ride: 'Confirm Ride',
      route_details: 'Route Details',
      available_vehicle: 'Available Vehicle',
      luggage_options: 'Luggage / Package Weight (Optional)',
      luggage_weight: 'Luggage weight: {w} kg',
      gst_tax: 'GST (5%)',
      total_fare: 'Total Fare',
      book_ticket_btn: 'Book Ticket',
      back_to_search: 'Back to Search',
      distance_unknown: 'Distance Unknown',
      km_from_you: '{dist} km from you',
      no_shops_found: 'No matching shops found',
      no_shops_found_sub: 'Try searching for a different category or store name in your area.',
      service_portfolio: 'Service Portfolio',
      digital_catalog: 'Digital Catalog',
      available_services: 'Available Services',
      available_products: 'Available Products',
      out_of_stock: 'Out of Stock',
      no_services_available: 'No services available right now.',
      no_products_available: 'No products available right now.'
    }
  },
  hi: {
    name: 'हिंदी',
    dir: 'ltr',
    translations: {
      welcome: 'पासवाला में आपका स्वागत है',
      tagline: 'आपका भरोसेमंद पड़ोसी केंद्र',
      near_shops: 'पास की दुकानें',
      expert_services: 'स्थानीय विशेषज्ञ',
      community: 'समुदाय',
      essentials: 'दैनिक आवश्यकताएं',
      search_placeholder: 'दुकानें या सेवाएँ खोजें...',
      add_to_cart: 'कार्ट में जोड़ें',
      book_now: 'अभी बुक करें',
      checkout: 'चेकआउट',
      cart_empty: 'आपकी कार्ट खाली है',
      savings: 'आपने बचाए',
      vendor_mode: 'विक्रेता मोड पर स्विच करें',
      profile: 'प्रोफ़ाइल',
      logout: 'साइन आउट',
      location: 'वर्तमान स्थान',
      change_location: 'स्थान बदलें',
      trust_badge: '{n} पड़ोसियों का भरोसा',
      new_order: 'नया ऑर्डर',
      total: 'कुल',
      items: 'वस्तुएं',
      ai_expert: 'एआई विशेषज्ञ से चैट करें',
      
      // Profile Page Translations
      appearance: 'दिखावट',
      dark_mode: 'डार्क मोड',
      switch_theme: 'थीम शैली बदलें',
      account_activity: 'खाता और गतिविधि',
      order_history: 'ऑर्डर इतिहास',
      view_past_bookings: 'अपनी पुरानी बुकिंग देखें',
      passwala_wallet: 'पासवाला वॉलेट',
      manage_credits: 'अपने क्रेडिट प्रबंधित करें',
      delivery_address: 'डिलिवरी का पता',
      manage_locations: 'अपने स्थान प्रबंधित करें',
      data_safety_deletion: 'डेटा सुरक्षा और हटाना',
      manage_data_rights: 'अपने डेटा अधिकारों को प्रबंधित करें',
      privacy_security: 'गोपनीयता और सुरक्षा',
      manage_security: 'अपनी सुरक्षा प्रबंधित करें',
      help_support: 'सहायता और समर्थन',
      support_24_7: '24/7 सहायता उपलब्ध',
      settings: 'सेटिंग्स',
      app_preferences: 'ऐप प्राथमिकताएं',
      logout_session: 'अपने सत्र से लॉगआउट करें',
      delete_account_permanently: 'स्थायी रूप से खाता हटाएं',
      
      // Hub Translations
      verified_pros: 'सत्यापित स्थानीय पेशेवर',
      best_stores: 'सर्वश्रेष्ठ स्थानीय दुकानें',
      city_rides: 'शहर की सवारी',
      city_rides_sub: 'अहमदाबाद परिवहन',
      event_tickets: 'इवेंट टिकट',
      event_tickets_sub: 'अहमदाबाद के कार्यक्रम',
      join_floor_chat: 'चैट में शामिल हों',
      book_pro: 'प्रो बुक करें',
      book_now_caps: 'अभी बुक करें',
      book_ticket: 'टिकट बुक करें',
      
      // Near Shops / Experts Translations
      search_shops_items: 'दुकानें, सामान खोजें...',
      search_experts_services: 'विशेषज्ञ, सेवाएँ खोजें...',
      all: 'सभी',
      general_store: 'जनरल स्टोर',
      grocery: 'किराना',
      vegetables: 'सब्जियां',
      dairy: 'डेयरी',
      bakery: 'बेकरी',
      plumbing: 'प्लंबिंग',
      electrical: 'इलेक्ट्रिकल',
      ac_service: 'एसी सर्विस',
      cleaning: 'सफाई',
      carpentry: 'बढ़ईगीरी',
      ac_appliance: 'एसी और उपकरण',
      painting: 'पेंटिंग',
      describe_issue: 'समस्या का वर्णन करें (जैसे कि नल टपकना, एसी सेवा)...',
      inspection_fee: 'निरीक्षण शुल्क',
      km_away: '{dist} किमी दूर',
      you_are_here: 'आप यहाँ हैं',
      view_services: 'सेवाएँ देखें',
      view_catalog: 'कैटलॉग देखें',
      book_expert: 'विशेषज्ञ बुक करें',
      pickup_location: 'पिकअप स्थान',
      dropoff_location: 'ड्रॉप-ऑफ स्थान',
      search_pickup_placeholder: 'पिकअप स्थान खोजें या मानचित्र पर टैप करें...',
      search_dropoff_placeholder: 'ड्रॉप-ऑफ स्थान खोजें या मानचित्र पर टैप करें...',
      popular_areas: 'अहमदाबाद में लोकप्रिय क्षेत्र',
      search_available_rides: 'उपलब्ध सवारियां खोजें',
      confirm_ride: 'सवारी की पुष्टि करें',
      route_details: 'मार्ग विवरण',
      available_vehicle: 'उपलब्ध वाहन',
      luggage_options: 'सामान / पैकेज का वजन (वैकल्पिक)',
      luggage_weight: 'सामान का वजन: {w} किग्रा',
      gst_tax: 'जीएसटी (5%)',
      total_fare: 'कुल किराया',
      book_ticket_btn: 'टिकट बुक करें',
      back_to_search: 'खोज पर वापस जाएं',
      distance_unknown: 'दूरी अज्ञात',
      km_from_you: 'आपसे {dist} किमी',
      no_shops_found: 'कोई मेल खाती दुकानें नहीं मिलीं',
      no_shops_found_sub: 'अपने क्षेत्र में एक अलग श्रेणी या स्टोर नाम खोजने का प्रयास करें।',
      service_portfolio: 'सेवा पोर्टफोलियो',
      digital_catalog: 'डिजिटल कैटलॉग',
      available_services: 'उपलब्ध सेवाएं',
      available_products: 'उपलब्ध उत्पाद',
      out_of_stock: 'आउट ऑफ स्टॉक',
      no_services_available: 'अभी कोई सेवाएं उपलब्ध नहीं हैं।',
      no_products_available: 'अभी कोई उत्पाद उपलब्ध नहीं हैं।'
    }
  },
  gu: {
    name: 'ગુજરાતી',
    dir: 'ltr',
    translations: {
      welcome: 'પાસવાલામાં તમારું સ્વાગત છે',
      tagline: 'તમારા વિશ્વાસુ પડોશી હબ',
      near_shops: 'નજીકની દુકાનો',
      expert_services: 'સ્થાનિક નિષ્ણાતો',
      community: 'સમુદાય',
      essentials: 'દૈનિક જરૂરિયાતો',
      search_placeholder: 'દુકાનો કે સેવાઓ શોધો...',
      add_to_cart: 'કાર્ટમાં ઉમેરો',
      book_now: 'અત્યારે બુક કરો',
      checkout: 'ચેકઆઉટ',
      cart_empty: 'તમારી કાર્ટ ખાલી છે',
      savings: 'તમે બચાવ્યા',
      vendor_mode: 'વેન્ડર મોડ પર સ્વિચ કરો',
      profile: 'પ્રોફાઇલ',
      logout: 'સાઇન આઉટ',
      location: 'વર્તમાન સ્થાન',
      change_location: 'સ્થાન બદલો',
      trust_badge: '{n} પડોશીઓ દ્વારા વિશ્વાસ',
      new_order: 'નવો ઓર્ડર',
      total: 'કુલ',
      items: 'વસ્તુઓ',
      ai_expert: 'AI નિષ્ણાત સાથે ચેટ કરો',
      
      // Profile Page Translations
      appearance: 'દેખાવ',
      dark_mode: 'ડાર્ક મોડ',
      switch_theme: 'થીમ શૈલી બદલો',
      account_activity: 'ખાતું અને પ્રવૃત્તિ',
      order_history: 'ઓર્ડર ઇતિહાસ',
      view_past_bookings: 'તમારી ભૂતકાળની બુકિંગ જુઓ',
      passwala_wallet: 'પાસવાલા વોલેટ',
      manage_credits: 'તમારા ક્રેડિટ મેનેજ કરો',
      delivery_address: 'ડિલિવરી સરનામું',
      manage_locations: 'તમારા સ્થાનો મેનેજ કરો',
      data_safety_deletion: 'ડેટા સુરક્ષા અને કાઢી નાખવું',
      manage_data_rights: 'તમારા ડેટા અધિકારો મેનેજ કરો',
      privacy_security: 'ગોપનીયતા અને સુરક્ષા',
      manage_security: 'તમારી સુરક્ષા મેનેજ કરો',
      help_support: 'મદદ અને સપોર્ટ',
      support_24_7: '24/7 સપોર્ટ ઉપલબ્ધ',
      settings: 'સેટિંગ્સ',
      app_preferences: 'એપ્લિકેશન પસંદગીઓ',
      logout_session: 'તમારા સત્રમાંથી લોગઆઉટ કરો',
      delete_account_permanently: 'કાયમ માટે ખાતું કાઢી નાખો',
      
      // Hub Translations
      verified_pros: 'પ્રમાણિત સ્થાનિક વ્યાવસાયિકો',
      best_stores: 'શ્રેષ્ઠ પડોશી દુકાનો',
      city_rides: 'શહેરની સવારી',
      city_rides_sub: 'અમદાવાદ ટ્રાન્ઝિટ',
      event_tickets: 'ઇવેન્ટ ટિકિટ',
      event_tickets_sub: 'અમદાવાદ કાર્યક્રમો',
      join_floor_chat: 'ચેટમાં જોડાઓ',
      book_pro: 'પ્રો બુક કરો',
      book_now_caps: 'અત્યારે બુક કરો',
      book_ticket: 'ટિકિટ બુક કરો',
      
      // Near Shops / Experts Translations
      search_shops_items: 'દુકાનો, વસ્તુઓ શોધો...',
      search_experts_services: 'નિષ્ણાતો, સેવાઓ શોધો...',
      all: 'બધા',
      general_store: 'જનરલ સ્ટોર',
      grocery: 'કરિયાણું',
      vegetables: 'શાકભાજી',
      dairy: 'ડેરી',
      bakery: 'બેકરી',
      plumbing: 'પ્લમ્બિંગ',
      electrical: 'ઇલેક્ટ્રિકલ',
      ac_service: 'એસી સર્વિસ',
      cleaning: 'સફાઈ',
      carpentry: 'સુથારી કામ',
      ac_appliance: 'એસી અને ઉપકરણો',
      painting: 'પેઇન્ટિંગ',
      describe_issue: 'સમસ્યાનું વર્ણન કરો (જેમ કે નળ ટપકવો, એસી સેવા)...',
      inspection_fee: 'નિરીક્ષણ ફી',
      km_away: '{dist} કિમી દૂર',
      you_are_here: 'તમે અહીં છો',
      view_services: 'સેવાઓ જુઓ',
      view_catalog: 'કેટલોગ જુઓ',
      book_expert: 'નિષ્ણાત બુક કરો',
      pickup_location: 'પિકઅપ સ્થાન',
      dropoff_location: 'ડ્રોપ-ઓફ સ્થાન',
      search_pickup_placeholder: 'પિકઅપ સ્થાન શોધો અથવા નકશા પર ટેપ કરો...',
      search_dropoff_placeholder: 'ડ્રોપ-ઓફ સ્થાન શોધો અથવા નકશા પર ટેપ કરો...',
      popular_areas: 'અમદાવાદમાં લોકપ્રિય વિસ્તારો',
      search_available_rides: 'ઉપલબ્ધ સવારી શોધો',
      confirm_ride: 'સવારી કન્ફર્મ કરો',
      route_details: 'રૂટ વિગતો',
      available_vehicle: 'ઉપલબ્ધ વાહન',
      luggage_options: 'સામાન / પેકેજ વજન (વૈકલ્પિક)',
      luggage_weight: 'સામાનનું વજન: {w} કિગ્રા',
      gst_tax: 'GST (5%)',
      total_fare: 'કુલ ભાડું',
      book_ticket_btn: 'ટિકિટ બુક કરો',
      back_to_search: 'શોધ પર પાછા ફરો',
      distance_unknown: 'અજ્ઞાત અંતર',
      km_from_you: 'તમારાથી {dist} કિમી',
      no_shops_found: 'કોઈ મેળ ખાતી દુકાનો મળી નથી',
      no_shops_found_sub: 'તમારા વિસ્તારમાં એક અલગ કેટેગરી અથવા સ્ટોર નામ શોધવાનો પ્રયાસ કરો.',
      service_portfolio: 'સેવા પોર્ટફોલિયો',
      digital_catalog: 'ડિજિટલ કેટલોગ',
      available_services: 'ઉપલબ્ધ સેવાઓ',
      available_products: 'ઉપલબ્ધ પ્રોડક્ટ્સ',
      out_of_stock: 'આઉટ ઓફ સ્ટોક',
      no_services_available: 'હમણાં કોઈ સેવાઓ ઉપલબ્ધ નથી.',
      no_products_available: 'હમણાં કોઈ પ્રોડક્ટ્સ ઉપલબ્ધ નથી.'
    }
  },
  mr: {
    name: 'मराठी',
    dir: 'ltr',
    translations: {
      welcome: 'पासवाला मध्ये आपले स्वागत आहे',
      tagline: 'तुमचे विश्वसनीय शेजारी केंद्र',
      near_shops: 'जवळपासची दुकाने',
      expert_services: 'स्थानिक तज्ज्ञ',
      community: 'समुदाय',
      essentials: 'दैनंदिन गरजा',
      search_placeholder: 'दुकाने किंवा सेवा शोधा...',
      add_to_cart: 'कार्टमध्ये जोडा',
      book_now: 'आता बुक करा',
      checkout: 'चेकआउट',
      cart_empty: 'तुमची कार्ट रिकामी आहे',
      savings: 'तुम्ही वाचवले',
      vendor_mode: 'विक्रेता मोडवर स्विच करा',
      profile: 'प्रोफाइल',
      logout: 'साइन आउट',
      location: 'वर्तमान स्थान',
      change_location: 'स्थान बदला',
      trust_badge: '{n} शेजार्‍यांचा विश्वास',
      new_order: 'नवीन ऑर्डर',
      total: 'एकूण',
      items: 'वस्तू',
      ai_expert: 'AI तज्ज्ञांशी चॅट करा',
      
      // Profile Page Translations
      appearance: 'देखावा',
      dark_mode: 'डार्क मोड',
      switch_theme: 'थीम शैली बदला',
      account_activity: 'खाते आणि क्रियाकलाप',
      order_history: 'ऑर्डर इतिहास',
      view_past_bookings: 'तुमचे मागील बुकिंग पहा',
      passwala_wallet: 'पासवाला वॉलेट',
      manage_credits: 'तुमचे क्रेडिट व्यवस्थापित करा',
      delivery_address: 'वितरणाचा पत्ता',
      manage_locations: 'तुमची ठिकाणे व्यवस्थापित करा',
      data_safety_deletion: 'डेटा सुरक्षा आणि हटवणे',
      manage_data_rights: 'तुमचे डेटा अधिकार व्यवस्थापित करा',
      privacy_security: 'गोपनीयता आणि सुरक्षा',
      manage_security: 'तुमची सुरक्षा व्यवस्थापित करा',
      help_support: 'मदत आणि समर्थन',
      support_24_7: '24/7 समर्थन उपलब्ध',
      settings: 'सेटिंग्ज',
      app_preferences: 'अॅप प्राधान्ये',
      logout_session: 'तुमच्या सत्रातून लॉगआउट करा',
      delete_account_permanently: 'खाते कायमचे हटवा',
      
      // Hub Translations
      verified_pros: 'प्रमाणित स्थानिक व्यावसायिक',
      best_stores: 'सर्वोत्तम शेजारची दुकाने',
      city_rides: 'शहर सवारी',
      city_rides_sub: 'अहमदाबाद ट्रान्झिट',
      event_tickets: 'इव्हेंट तिकिटे',
      event_tickets_sub: 'अहमदाबाद कार्यक्रम',
      join_floor_chat: 'चॅटमध्ये सामील व्हा',
      book_pro: 'प्रो बुक करा',
      book_now_caps: 'आता बुक करा',
      book_ticket: 'तिकीट बुक करा',
      
      // Near Shops / Experts Translations
      search_shops_items: 'दुकाने, वस्तू शोधा...',
      search_experts_services: 'तज्ज्ञ, सेवा शोधा...',
      all: 'सर्व',
      general_store: 'जनरल स्टोअर',
      grocery: 'किराणा',
      vegetables: 'भाज्या',
      dairy: 'डेअरी',
      bakery: 'बेकरी',
      plumbing: 'प्लंबिंग',
      electrical: 'इलेक्ट्रिकल',
      ac_service: 'एसी सर्व्हिस',
      cleaning: 'सफाई',
      carpentry: 'सुतारकाम',
      ac_appliance: 'एसी आणि उपकरणे',
      painting: 'पेंटिंग',
      describe_issue: 'समस्येचे वर्णन करा (जसे की नळ गळणे, एसी सेवा)...',
      inspection_fee: 'तपासणी शुल्क',
      km_away: '{dist} किमी दूर',
      you_are_here: 'तुम्ही इथे आहात',
      view_services: 'सेवा पहा',
      view_catalog: 'कॅटलॉग पहा',
      book_expert: 'तज्ज्ञ बुक करा',
      pickup_location: 'पिकअप ठिकाण',
      dropoff_location: 'ड्रॉप-ऑफ ठिकाण',
      search_pickup_placeholder: 'पिकअप ठिकाण शोधा किंवा नकाशावर टॅप करा...',
      search_dropoff_placeholder: 'ड्रॉप-ऑफ ठिकाण शोधा किंवा नकाशावर टॅप करा...',
      popular_areas: 'अहमदाबादमधील लोकप्रिय भाग',
      search_available_rides: 'उपलब्ध वाहने शोधा',
      confirm_ride: 'सवारीची पुष्टी करा',
      route_details: 'मार्ग तपशील',
      available_vehicle: 'उपलब्ध वाहन',
      luggage_options: 'सामान / पॅकेजचे वजन (पर्यायी)',
      luggage_weight: 'सामान वजन: {w} किलो',
      gst_tax: 'जीएसटी (5%)',
      total_fare: 'एकूण भाडे',
      book_ticket_btn: 'तिकीट बुक करा',
      back_to_search: 'शोध वर परत जा',
      distance_unknown: 'अंतर माहीत नाही',
      km_from_you: 'तुमच्यापासून {dist} किमी',
      no_shops_found: 'कोणतीही जुळणारी दुकाने आढळली नाहीत',
      no_shops_found_sub: 'तुमच्या भागातील वेगळी श्रेणी किंवा स्टोअरचे नाव शोधण्याचा प्रयत्न करा.',
      service_portfolio: 'सेवा पोर्टफोलिओ',
      digital_catalog: 'डिजिटल कॅटलॉग',
      available_services: 'उपलब्ध सेवा',
      available_products: 'उपलब्ध उत्पादने',
      out_of_stock: 'आउट ऑफ स्टॉक',
      no_services_available: 'सध्या कोणत्याही सेवा उपलब्ध नाहीत.',
      no_products_available: 'सध्या कोणतीही उत्पादने उपलब्ध नाहीत.'
    }
  },
  ta: {
    name: 'தமிழ்',
    dir: 'ltr',
    translations: {
      welcome: 'பாஸ்வாலாவிற்கு வரவேற்கிறோம்',
      tagline: 'உங்கள் நம்பகமான அண்டை மையம்',
      near_shops: 'அருகிலுள்ள கடைகள்',
      expert_services: 'உள்ளூர் நிபுணர்கள்',
      community: 'சமூகம்',
      essentials: 'தினசரி தேவைகள்',
      search_placeholder: 'கடைகள் அல்லது சேவைகளைத் தேடுங்கள்...',
      add_to_cart: 'கார்ட்டில் சேர்',
      book_now: 'இப்போது முன்பதிவு செய்',
      checkout: 'செக் அவுட்',
      cart_empty: 'உங்கள் கார்ட் காலியாக உள்ளது',
      savings: 'நீங்கள் சேமித்தது',
      vendor_mode: 'விற்பனையாளர் பயன்முறைக்கு மாறவும்',
      profile: 'சுயவிவரம்',
      logout: 'வெளியேறு',
      location: 'தற்போதைய இடம்',
      change_location: 'இருப்பிடத்தை மாற்றவும்',
      trust_badge: '{n} அண்டை வீட்டார்களால் நம்பப்படுகிறது',
      new_order: 'புதிய ஆர்டர்',
      total: 'மொத்தம்',
      items: 'பொருட்கள்',
      ai_expert: 'AI நிபுணருடன் அரட்டையடிக்கவும்',
      
      // Profile Page Translations
      appearance: 'தோற்றம்',
      dark_mode: 'இருண்ட பயன்முறை',
      switch_theme: 'தீம் பாணியை மாற்றவும்',
      account_activity: 'கணக்கு & செயல்பாடு',
      order_history: 'ஆர்டர் வரலாறு',
      view_past_bookings: 'உங்கள் கடந்தகால முன்பதிவுகளைப் பார்க்கவும்',
      passwala_wallet: 'பாஸ்வாலா வாலட்',
      manage_credits: 'உங்கள் வரம்புகளை நிர்வகிக்கவும்',
      delivery_address: 'டெலிவரி முகவரி',
      manage_locations: 'உங்கள் இருப்பிடங்களை நிர்வகிக்கவும்',
      data_safety_deletion: 'தரவு பாதுகாப்பு & நீக்கம்',
      manage_data_rights: 'உங்கள் தரவு உரிமைகளை நிர்வகிக்கவும்',
      privacy_security: 'தனியுரிமை & பாதுகாப்பு',
      manage_security: 'உங்கள் பாதுகாப்பை நிர்வகிக்கவும்',
      help_support: 'உதவி & ஆதரவு',
      support_24_7: '24/7 ஆதரவு கிடைக்கும்',
      settings: 'அமைப்புகள்',
      app_preferences: 'பயன்பாட்டு விருப்பத்தேர்வுகள்',
      logout_session: 'உங்கள் அமர்விலிருந்து வெளியேறவும்',
      delete_account_permanently: 'கணக்கை நிரந்தரமாக நீக்கு',
      
      // Hub Translations
      verified_pros: 'சரிபார்க்கப்பட்ட உள்ளூர் வல்லுநர்கள்',
      best_stores: 'சிறந்த அண்டை கடைகள்',
      city_rides: 'நகர சவாரிகள்',
      city_rides_sub: 'அகமதாபாத் போக்குவரத்து',
      event_tickets: 'நிகழ்ச்சி டிக்கெட்டுகள்',
      event_tickets_sub: 'அகமதாபாத் நிகழ்வுகள்',
      join_floor_chat: 'அரட்டையில் இணையுங்கள்',
      book_pro: 'நிபுணரை பதிவு செய்',
      order_now: 'இப்போது ஆர்டர் செய்',
      book_ticket: 'டிக்கெட் முன்பதிவு செய்',
      book_now_caps: 'இப்போது முன்பதிவு செய்',
      
      // Near Shops / Experts Translations
      search_shops_items: 'கடைகள், பொருட்களைத் தேடுங்கள்...',
      search_experts_services: 'நிபுணர்கள், சேவைகளைத் தேடுங்கள்...',
      all: 'அனைத்தும்',
      general_store: 'பொது அங்காடி',
      grocery: 'மளிகை',
      vegetables: 'காய்கறிகள்',
      dairy: 'பால் பண்ணை',
      bakery: 'பேக்கரி',
      plumbing: 'குழாய் வேலை',
      electrical: 'மின்சாரம்',
      ac_service: 'ஏசி சேவை',
      cleaning: 'சுத்தம் செய்தல்',
      carpentry: 'தச்சு வேலை',
      ac_appliance: 'ஏசி & உபகரணங்கள்',
      painting: 'பெயிண்டிங்',
      describe_issue: 'சிக்கலை விவரிக்கவும் (எ.கா. குழாய் கசிவு, ஏசி சேவை)...',
      inspection_fee: 'ஆய்வு கட்டணம்',
      km_away: '{dist} கிமீ தொலைவில்',
      you_are_here: 'நீங்கள் இங்கே இருக்கிறீர்கள்',
      view_services: 'சேவைகளைப் பார்க்கவும்',
      view_catalog: 'பட்டியலைப் பார்க்கவும்',
      book_expert: 'நிபுணரை பதிவு செய்',
      pickup_location: 'பிக்கப் இருப்பிடம்',
      dropoff_location: 'டிராப் இருப்பிடம்',
      search_pickup_placeholder: 'பிக்கப் இடத்தை தேடவும் அல்லது வரைபடத்தில் தட்டவும்...',
      search_dropoff_placeholder: 'டிராப் இடத்தை தேடவும் அல்லது வரைபடத்தில் தட்டவும்...',
      popular_areas: 'அகமதாபாத்தில் பிரபலமான பகுதிகள்',
      search_available_rides: 'கிடைக்கக்கூடிய சவாரிகளைத் தேடுங்கள்',
      confirm_ride: 'சவாரியை உறுதிப்படுத்துக',
      route_details: 'பயண வழி விவரங்கள்',
      available_vehicle: 'கிடைக்கக்கூடிய வாகனம்',
      luggage_options: 'லக்கேஜ் / பார்சல் எடை (விருப்பம்)',
      luggage_weight: 'லக்கேஜ் எடை: {w} கிலோ',
      gst_tax: 'ஜிஎஸ்டி (5%)',
      total_fare: 'மொத்த கட்டணம்',
      book_ticket_btn: 'டிக்கெட் பதிவு செய்',
      back_to_search: 'தேடலுக்குத் திரும்பு',
      distance_unknown: 'தொலைவு தெரியவில்லை',
      km_from_you: 'உங்களிடமிருந்து {dist} கிமீ',
      no_shops_found: 'பொருந்தும் கடைகள் எதுவும் இல்லை',
      no_shops_found_sub: 'உங்கள் பகுதியில் வேறு வகை அல்லது கடையின் பெயரைத் தேட முயற்சிக்கவும்.',
      service_portfolio: 'சேவை போர்ட்ஃபோலியோ',
      digital_catalog: 'டிஜிட்டல் பட்டியல்',
      available_services: 'கிடைக்கக்கூடிய சேவைகள்',
      available_products: 'கிடைக்கக்கூடிய தயாரிப்புகள்',
      out_of_stock: 'ஸ்டாக் இல்லை',
      no_services_available: 'தற்போது சேவைகள் எதுவும் இல்லை.',
      no_products_available: 'தற்போது தயாரிப்புகள் எதுவும் இல்லை.'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('passwala_lang') || 'en';
  });

  const t = (key) => {
    return languages[currentLanguage].translations[key] || languages.en.translations[key] || key;
  };

  const changeLanguage = (lang) => {
    if (languages[lang]) {
      setCurrentLanguage(lang);
      localStorage.setItem('passwala_lang', lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, changeLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
